---
title: "Actions Towards Others"
---

## Be Like Fingers of One Hand, Limbs of One Body

Associate with each other in the spirit of joy and fragrance

## Good Deeds

Adorn yourselves with the ornament of deeds. Support the Lord of Creation with good deeds.

The crown of deeds is proclaiming the cause of God.

## Providing for Others

Provide for relatives

Provide for the poor

Provide for the needy

## Hospitality

Each person must provide hospitality each month, even if only water is served. Hospitality is the act of inviting another to your home, where you serve them and make them feel at home. The purpose is to bring hearts together.

## Do Not Be Wicked with Power

## Differ On Any Matter

If you and another have a difference regarding any matter, Baha'u'llah instructs us to consult His Revelation, for it is sufficient to all peoples of the world. This passage also clearly demonstrates there is not need for outside interpretation, or other people's teachings to be used as an equivalent to Baha'u'llah's teachings.

We are to rely on Baha'u'llah's Revelation.

## Violent Acts

### Murder

Murder is prohibited. This is the first clear prohibition in the Kitab-i-Aqdas. In the West, there are different definitions for homicide and murder, along with defining intention. In the Kitab-i-Aqdas, Baha'u'llah uses the Arabic word "al-qatl" (القتل), where upon the various types of murder add onto the base word qatl.

This means any loss of human life by another human is prohibited, whether intended or not. The impact of any loss of life by another person is too great. It weakens the fabric of the community, causes trauma, distrust, and potentially thoughts and feelings which can betray which God desires for us.

In another sense, it is an act of shirk, the Arabic concept of joining partners with God. Ultimately God has all power of creation, but murder is where a person tries to take this power away from God. The person is deciding when another's spiritual journey will begin the next stage.

The punishment for the intentional act of murder is death, with the option for life imprisonment.

### Injuries to the Head and Body

Prohibited to assault anyone and cause injuries to the head and body. This includes intentional acts but could possibly also include unintentional acts, such as accidents or from gross negligence.

### Retaliation

Do not object to another, nor take one life for another.

## Oppression

Oppression towards another can take various forms. A potential list can include:

1.  Physical Abuse

2.  Emotional and Psychological Abuse

3.  Economic and Financial Control

4.  Coercion and the Deprivation of Autonomy

5.  Cultural and Religious Oppression

6.  Neglect and Abandonment

7.  Racial and Ethnic Oppression

8.  Gender and Sexual Oppression

9.  Political Oppression

10. Environmental Oppression

11. Cultural and Intellectual Oppression

12. Oppression of Individuals with Disabilities

13. Oppression in Healthcare

### Tyranny

### Buying and Selling People

It is forbidden to buy or sell any person.

## Sexual Acts

### Adultery

Adultery is prohibited. This prohibition does not necessarily mean all kinds of sexual acts are forbidden, despite being based on the Arabic word zina. Adultery is when a married person consents to sexual acts with a person who is not their spouse. Adultery can also include when a non-married person consents to sexual acts with a person they know is married.

There are many reasons why adultery is prohibited. The first one is that marriage is usually considered a promise to God and is a sacred union. Violating this promise also signifies a broken promise to God. Perhaps the most important reason is the impact it can have upon the family. Within marriage, negative actions spouses take against each other have negative consequences for the children of the spouses. Adultery can break the bonds of affection for the married couple and betray their mutual ability to provide a safe, nurturing, and healthy environment for children to grow up in.

Adultery is punishable by the House of Justice. For the 1st offense, 9 mithqáls of gold is to be paid to the House of Justice. This is paid by the man and also paid by the woman. For the 2nd offense, the fine is doubled to 18 mithqáls. To understand the valuation, the box below can show the current value of gold. 9 mithqáls is approximately 38.25g, so you would take the value of gold per gram and multiply it by 38.25, according to the currency you use. The default is US Dollars.

<iframe src="https://www.kitco.com/gold-price-today-usa/" width="600" height="400">

</iframe>

The third offence is subjected to a humiliating punishment. The specifics of this has not been clarified, but could be done so by a House of Justice if needed. Baha'u'llah says any person afflicted by sin should repent, although this does not necessarily absolve the person from being punished by the House of Justice.

### Lewdness

### Pederasty

## Social Acts

### Backbiting

Backbiting is prohibited. Backbiting is speaking about the negative traits and actions of another person without the person being present. What is being discussed can be true, but the person does not have an ability to defend themselves or contribute what they also believe is true.

Additionally, Baha'u'llah regularly taught us to refrain from discussing the sins of others, because we are also sinners. This prohibition does not mean a person cannot discuss truthful facts with the person present, but there must be a greater purpose. For example, the previous prohibition regarding all forms of murder. Say you observed a community member dumping something unknown into a river used for drinking water. Another in the community becomes ill and dies due to a toxic substance in the water. Backbiting would be telling others you saw the person dumping toxic chemicals into the water, and the person is not there. The person is unable to say what they put into the river, why, or anything else. The person observed could be at risk of retributive actions, which again puts the greater community at risk of non-spiritual perspectives and actions. Instead, the person should go to the person in question and say "I saw you put some substance into the river. What was it?" The response is up to the truthfulness of who was being asked, but it could keep someone from being falsely accused.

The backbiter could have gotten someone accused of murder, or viewed by community members as someone capable of murder even if they are found not guilty. This harm exists in even less obviously impactful situations.

Now, if there is an investigation into the cause of death, it is not prohibited to provide facts. Honestly state what you observed, without adding assumptions.

Finally, backbiting also has a perspective of a person being more consumed with the faults of others while lacking the ability to see the faults in themselves. With the People of Glory being told to bring themselves to account each day, we can see Baha'u'llah is very concerned with how we view ourselves and others. Do we have empathy? Do we act with love?

### Slander

Slander is prohibited. Slander is the knowingly false negative information about another. Slander is purposefully designed to degrade another's reputation and can also cause substantial harm to the victim. The impacts of this can lead to lower earnings potential, ruined personal and professional relationships, and less ability to sincerely be positive contributors to their community. It would be difficult to have a healthy assembly of the People of Glory if members are being subjected to backbiting and slander.

### Do Not Cause Corruption

### Do Not Cause Enmity

### Reconcile Differences

### Do Not Boast Over Another

## Property Acts

### Arson

The deliberate burning of a house is forbidden. The punishment is to burn the arsonist. The alternate punishment is life imprisonment.

### Stealing

Stealing is forbidden and is punishable by the Houses of Justice. Penalties include banishment, imprisonment, and for the third offense, a mark is to be placed on the forehead of the thief.

## Environmental Acts

### Do Not Corrupt the Earth

## Seeking Forgiveness From Others

Baha'u'llah forbids anyone to seek forgiveness from another as a religious duty. Only God can grant forgiveness if you repent from a sin.

This command also helps assure there is no hierarchy among the people of the community. This keeps one from exalting themselves over you, and also assures another does not place you in a position above them. We are all equals, born with a noble soul.
