---
title: "Appendix A: Names of God"
---

The following is a listing of the nineteen groups of the Names of God and the names associated with each group:

-   Subtlety
    -   Name: Most Subtle
-   Manifestation
    -   Name: Manifest
-   Knowledge
    -   Name: All Knowing
    -   Name: All Informed
    -   Name: Wise
    -   Name: Knower of All Things
-   Creation
    -   Name: Dawning Place
    -   Name: Creator
-   Power
    -   Name: Almighty
    -   Name: All Powerful
    -   Name: All Capable
    -   Name: All Subduing
    -   Name: All Sufficient
-   Lordship
    -   Name: Lord
-   Justice
    -   Name: Judge
    -   Name: Just
    -   Name: Reckoner
-   Exaltation
    -   Name: Most Exalted
    -   Name: Most High
    -   Name: Great
    -   Name: Majestic
    -   Name: Most Glorious
    -   Name: Greatest Infallibility
-   Independence
    -   Name: Self Sufficient
    -   Name: Self Subsisting
    -   Name: Independent
-   Command
    -   Name: Commander
    -   Name: Ordainer
    -   Name: Fulfiller
-   Counsel
    -   Name: Counselor
    -   Name: Speaker
    -   Name: Source of Inspiration
-   Faithfulness
    -   Name: Trustworthy
    -   Name: Faithful Guardian
-   Praise
    -   Name: All Praised
    -   Name: Praised
    -   Name: Praiseworthy
-   Love
    -   Name: Beloved
    -   Name: Loving
    -   Name: Gracious
-   Forgiveness
    -   Name: All Forgiving
    -   Name: Ever Forgiving
    -   Name: Oft Forgiving
-   Mercy
    -   Name: All Merciful
    -   Name: Most Merciful
    -   Name: Most Compassionate
-   Generosity
    -   Name: All Bountiful
    -   Name: Bestower
    -   Name: Most Generous
    -   Name: Most Bountiful
-   Sovereignty
    -   Name: Sovereign
    -   Name: Lord of Dominion
    -   Name: Ruler
    -   Name: Master
-   Purity
    -   Name: Purest
    -   Name: True
    -   Name: One

{{< pagebreak >}}
