---
title: "Appendix 1: Names of God"
---

The following is a list of the 19 groups of names of God and names which fall within them

1.  Subtlety - Most Subtle

2.  Manifestation - Manifest

3.  Knowledge - All-Knowing, All-Informed, Wise, Knower of All Things

4.  Creation - Dawning Place, Creator

5.  Power - Almighty, All-Powerful, All-Capable, All-Subduing, All-Sufficient

6.  Lordship - Lord

7.  Justice - Judge, Just, Reckoner

8.  Exaltation - Most Exalted, Most High, Great, Majestic, Most Glorious, Greatest Infallibility

9.  Independence - Self-Sufficient, Self-Subsisting, Independent

10. Command - Commander, Ordainer, Fulfiller

11. Counsel - Counselor, Speaker, Source of Inspiration

12. Faithfulness - Trustworthy, Faithful Guardian

13. Praise - All-Praised, Praised, and Praiseworthy

14. Love - Beloved, Loving, Gracious

15. Forgiveness - All-Forgiving, Ever-Forgiving, Oft-Forgiving

16. Mercy - All-Merciful, Most Merciful, Most Compassionate

17. Generosity - All-Bountiful, Bestower, Most Generous, Most Bountiful

18. Sovereignty - Sovereign, Lord of Dominion, Ruler, Master

19. Purity - Purest, True, One

{{< pagebreak >}}
