---
title: "The Badi Calendar"
---

## Ayyam-i-Ha (Days of Giving)

Also known as the intercalary days, which are not bound by the limits of the year and its months.

Provide for yourself

Provide for relatives

Provide for the poor

Provide for the needy

Exalt the Lord with joy and gladness

Magnify the Lord with Joy and gladness

Glorify the Lord with Joy and gladness

## Monthly Acts

Provide hospitality, even if only water is served.

## Ala

Fast the entire month

## Baha

### 1 Baha - Naw-Ruz - Festival

The second festival is the day when We raised up the one who announced to the people this name by which the dead were raised to life, and all in the heavens and the earth, as well as those who came after, were gathered.

Blessed is the one who attains the first day of the month of Bahá, which God has made for this great Name. Blessed is the one who manifests God’s bounty upon themselves on this day, for they are among those who show gratitude to God through their actions, which demonstrate His favor that encompasses the worlds. Say: It is the foremost of months and its beginning, and in it the breath of life passes over all created things. Blessed is the one who encounters it with spirit and joy, for we bear witness that they are among the victorious.

## **Ridván:** **13 Jalál to 5 Jamál**

The Greatest Festival is the sovereign of all festivals. O people, remember God's bounty upon you, for when you were asleep, He awakened you with the breezes of revelation and made known to you His clear and straight path.

### Ridván (Day 1 - **13 Jalál)**

Baha'u'llah manifested the most beautiful names and the highest attributes. All things have been immersed in the ocean of purity from the 1st day of Ridván.

It is a bounty so that you may associate with the followers of other religions and proclaim the Cause of your Lord. It is the crown of deeds.
