---
title: "Belief in the Human Soul"
---

## Chapter Introduction

The Kitab-i-Aqdas regularly describes the human soul and the station of humans and humanity. Baha'u'llah does not explicitly state a belief in the human soul is required in the Kitab-i-Aqdas or other writing, but like the belief in God, it is strongly implied. This will be the second foundation of this book upon which the Kitab-i-Aqdas rests upon.

The soul is an idea which is quite cross-cultural in that many distinct traditions describe the human soul in some way or another. Chapter 1 described how God is the creator of everything, is eternal, and other qualities which would testify to how distinct and seemingly disconnected cultures include such similar ideas. Each tradition may not say the exact same thing about the soul, such as the Hindu progress of the soul through various physical lifeforms or the Platonic concept of the distinct human soul, but the foundations of truth are all there. This chapter could potentially serve as a bridge between these various traditions and provide a clear understanding of the soul and allow cross-cultural and interfaith dialogue to exist. After all, we are all equally human.

This chapter will be divided into four main sections: the Reality of the Human Soul, the Unique Nature of the Soul, the Inner Struggles of the Soul, and the Fate of the Soul. These sections are derived from the Kitab-i-Aqdas as the primary source document. Any supplementation from other sources from the Bab and Baha'u'llah will be noted.

## **The Reality of the Human Soul**

The first belief is the fact the human soul exists and is real. The soul in its form did not eternally pre-exist but was created by God. Baha'u'llah says simply we are created from water.[^belief-in-the-human-station-1] Baha'u'llah says water is one of the key components of all creation, celestial and terrestial, along with fire, air, and earth as they combine to make heat, moisture, cold, and dryness. [^belief-in-the-human-station-2] He also describes various kinds of water used in the creation of spirit, soul, and body in the same tablet. Baha'u'llah describes the water of semen as being pure, not something itself which needs purified. [^belief-in-the-human-station-3] Water, regardless of the source, is the foundation of all life.

[^belief-in-the-human-station-1]: Kitab-i-Aqdas Verse #148

[^belief-in-the-human-station-2]: Tablet of the Light Verses and Disjointed Letters

[^belief-in-the-human-station-3]: Kitab-i-Aqdas Verse #74

Baha'u'llah says that we are brought to life with a spirit from God[^belief-in-the-human-station-4], through the divine breath.[^belief-in-the-human-station-5] All living things are animated by this breath of God, which is spirit itself. This breath works as the catalyst upon water and the other elements, giving life to everything living. This includes organic entities such as animals, plants, bacteria, and other things biology classifies as living. This spirit also is within other non-organic objects such as the sun, the moon, earth, and other objects whose lifespan endures for millions and billions of years. The spirit animates the body and it animates the human soul as well as the souls of endless creatures.[^belief-in-the-human-station-6] The soul is not created at the moment of conception, as it does require the body to be the vessel and for its elements to reach a stage of maturity. Baha'u'llah does not exactly define when this exactly occurs but this could occur during embryonic of fetal development.

[^belief-in-the-human-station-4]: Kitab-i-Aqdas Verse #73

[^belief-in-the-human-station-5]: Kitab-i-Aqdas Verse #158

[^belief-in-the-human-station-6]: Suriy-i-Rais (Tablet to the Chief) - This tablet provides a very good sermon about the nature of the soul

The human soul is the innermost part of ourselves. The soul provides the "direction of the spirit towards one orientation over others."[^belief-in-the-human-station-7] The soul can be ignited by fire of the love of God or by one's own whim. This expresses the soul itself has free will. Despite God's names and attributes of power and knowledge, God has imparted every thing made of spirit freedom to move as it wishes, according to its temperament and direction.

[^belief-in-the-human-station-7]: Suriy-i-Rais

Baha'u'llah expresses the all souls and all humans are Signs of the divine reality.[^belief-in-the-human-station-8] In Chapter 1, we learned how these signs are subtle and when manifested, are a foundation for us in understanding God and His purpose. The soul is also a sign, functioning as a mirror capable of reflecting God's reality. This is true for all people.[^belief-in-the-human-station-9] The names and attributes are manifested in the human soul.[^belief-in-the-human-station-10] This mirrorship is a way to recognize God within us.[^belief-in-the-human-station-11] These manifestations of Signs can occur in the same way God's names and attributes can also be believed in, perhaps in stages or through periods of continued realization.

[^belief-in-the-human-station-8]: Kitab-i-Aqdas Verse #72

[^belief-in-the-human-station-9]: Kitab-i-Badi - This book offers an in-depth explanation of what it means to be a mirror

[^belief-in-the-human-station-10]: Kitab-i-Iqan (Book of Certitude) - Another great source about the potentials of the soul

[^belief-in-the-human-station-11]: The Qur'an: “We shall show them Our signs in the horizons and within themselves until it becomes clear to them that it is the truth.” Also repeated in the Persian Bayan, the Seven Valleys, and the Kitab-i-Iqan.

## **The Unique Nature of the Soul**

Baha'u'llah describes the body as being a temple, and the collection of all people as being temples of humankind.[^belief-in-the-human-station-12] The figurative heart serves as a malleable lens within the body which serves to perceive divine truth. This helps a person with receptivity to God, which in turn helps a soul determine its destiny and spiritual path.

[^belief-in-the-human-station-12]: Kitab-i-Aqdas Verse #96

The Suriy-i-Haykal (Surah of the Temple) describes how Baha'u'llah, being a Manifestation of God, is a sacred vessel in the highest form. Every human body, although temporary, is also a sacred vessel although in a lower station than that of the Manifestation of God. The temple is temporary but is a place of worship and the development of spiritual qualities, according to its capacity as a mirror. This means the body is also capable of being used to nurture the soul, not just through material means but through being used for spiritually purposeful conduct and expression of divine attributes.

The soul is capable of having an exalted and noble station.[^belief-in-the-human-station-13] There are various stations and ranks a soul is capable of achieving. The soul itself was born noble[^belief-in-the-human-station-14] but requires effort to remain so by turning one's sight inward. There is no higher station than a person bearing witness to God.[^belief-in-the-human-station-15] The human soul's natural station is higher than that of animals, but can descend to the level of an animal's soul if it is neglected.[^belief-in-the-human-station-16]

[^belief-in-the-human-station-13]: Kitab-i-Aqdas Verse #120

[^belief-in-the-human-station-14]: The Arabic Hidden Words #13

[^belief-in-the-human-station-15]: Persian Bayan, Vahid 1 Gate 2

[^belief-in-the-human-station-16]: Persian Bayan, Vahid 5, Gate 14

Each person and each soul has its own capacity.[^belief-in-the-human-station-17] Not every person's soul will express the divine attributes and names equally or in the same exact way. They are expressed according to one's capacity.[^belief-in-the-human-station-18] This means every soul may have its own distinct strengths and weaknesses, bound by the human temple and its position in time and space. These different combinations of capacity, reflections of divine names and attributes, and effects of the body ensures every soul is distinct, much like the iris of the eye or the lines of the palm of the hand.

[^belief-in-the-human-station-17]: Kitab-i-Aqdas Verse #176

[^belief-in-the-human-station-18]: Kitab-i-Iqan

## **The Inner Struggles of the Soul**

Baha'u'llah describes a suspicious soul[^belief-in-the-human-station-19] as an opposition to one who uses reason. A suspicious soul could be someone who is ruled by doubt and is not sure who or what to trust. This doubt could be about God, God's purpose, or even their own purpose in life. This skepticism may exist even if truth or a path forward is evident. They may not understand the good in certain situations, understand the potential wisdom in difficult situations, and due to this, lack discipline to truly submit to God. This lack of discipline could lead to self-destructive acts and habits, which can lead a person further down the road of headlessness and suspicion. A suspicious soul could be someone who is deceptive, also known as hypocritical. They may outwardly portray belief but inwardly or in private has other beliefs and actions.

[^belief-in-the-human-station-19]: Kitab-i-Aqdas Verse #119

Baha'u'llah teaches these suspicions, as well as idols, act as idols.[^belief-in-the-human-station-20] These idols are the cause of humiliation and loss and keep a soul from ascending to the station they are rightful to inherit and claim. However, the Kitab-i-Aqdas does include the most simple perspective to help alleviate these inner struggles the soul may face. Baha'u'llah says all are servants.[^belief-in-the-human-station-21] The soul's fundamental purpose is in relation to the divine. All souls are servants. Belief not only in the soul, but in the soul's purpose as a servant of God. This establishes trust and humility, eliminating the symptoms of a suspicious soul such as distrust, skepticism, arrogance, or hypocrisy. Belief in servitude to God is the source of freedom for the soul[^belief-in-the-human-station-22] and reveals our true human rank.[^belief-in-the-human-station-23]

[^belief-in-the-human-station-20]: Lawh-i-Dunya (Tablet of the World)

[^belief-in-the-human-station-21]: Kitab-i-Aqdas Verse #72

[^belief-in-the-human-station-22]: Kitab-i-Aqdas Verse #125

[^belief-in-the-human-station-23]: Kitab-i-Aqdas Verse #120

## **The Fate of the Soul**

One matter which is not a matter of belief is the fact death of the body is inevitable. This is 100% guaranteed and is inescapable. It is also 100% fact once the body has died, the energy which used to be within the body no longer exists within it. It is also 100% fact and proven by science that energy does not merely disappear or cease to exist. The energy goes elsewhere. Where does it go?

Baha'u'llah reminds us we will return to dust.[^belief-in-the-human-station-24] The temple of the human body will end. The soul will take flight.[^belief-in-the-human-station-25] Taking flight symbolizes the soul's transcendence over material life, to a real place higher than where it was. The soul is also capable of transcending the human body even before the body has perished, if a person so desires and believes. "If you are a person of mystery and longing, take flight with the wings of the saints' aspirations so that you may see the secrets of the beloved and reach the light of the loved one. 'Indeed we belong to Allah, and indeed to Him we will return.'"[^belief-in-the-human-station-26] Baha'u'llah throughout His teachings reminds us the importance of the soul being allowed to take flight while the body is alive while constantly being aware of the inevitable flight when the body no longer exists. The first is not inevitable but desired by God, and the second is inevitable and desired for a believer and God. A suspicious soul might show fear for the second flight, fearing the end of everything. A soul in belief is prepared for flight.

[^belief-in-the-human-station-24]: Kitab-i-Aqdas Verse #148

[^belief-in-the-human-station-25]: Kitab-i-Aqdas Verse# 97

[^belief-in-the-human-station-26]: Haft Vadi (The Seven Valleys)

The desired journey of the soul is onboard the Crimson Ark.[^belief-in-the-human-station-27] It represents salvation and refuge, much like how the Noah's Ark led the people of the time to salvation. Belief in the salvation of the soul during the life of the body and after is important, especially within the belief of all the names and attributes of God. The journey in the Crimson Ark requires belief in God, in all the names and attributes of God. The journey in the Crimson Ark requires belief that you have a soul. The journey in the Crimson Ark requires belief in everyone else also has a soul. The fate of the soul doesn't require only consideration of your own salvation, but in the salvation of others.[^belief-in-the-human-station-28] The fate of the soul requires a belief that other souls deserve salvation. All souls are capable of transcending the bounds of self and body. All souls are able to take flight.

[^belief-in-the-human-station-27]: Kitab-i-Aqdas Verse #84

[^belief-in-the-human-station-28]: BH00093 (Letters to the Land of Kha)

The next chapter will discuss the potential destinations of the soul, the worlds of God.
