---
title: "Belief in the Worlds of God"
---

## Introduction

Religious cosmology has always been a subject I have always found fascinating. Every culture in the world has a creation story where the world(s) come into existence, Earth is formed with the major elements from which life begins, and humanity is created. All of this creation has a divine aspect to it. There are elements of truth within all of these stories, whether you believe them to be legend, myth, or absolute sources of fact. They help shape identity, purpose, and help us understand our place within creation.

You will discover the cosmology expressed by Baha'u'llah within the Kitab-i-Aqdas and further elaborated upon in His other writings has elements which may seem familiar. There will also be elements which seem strange, depending on your cultural perspective. I feel the Zoroastrian and Hindu traditions will find the closest relationship to the cosmology of Baha'u'llah, but even then, what is expressed by Baha'u'llah (as well as the Primal Point) is completely unique.

Belief in the worlds of God, while again not being explicitly expressed as required by the Kitab-i-Aqdas, is vital to the belief in the Cause of God. The journey of the soul must go somewhere. Pre-existence must had an origin. I hope this chapter will help unlock some of these mysteries and fortify the belief in the worlds of God. This belief is another foundation upon which the spiritual journey of individuals and our systems of organization rests upon. Our journey depends on this belief.

## Nature of the Worlds

The Kitab-i-Aqdas describes many worlds specifically. There is the lesser world, the greater world, spiritual worlds, heaven, and various kingdoms of these worlds. To introduce the nature of the worlds, I want to start with a long passage from the Suriy-i-Wafa (Tablet to Vafa).

> As for what you asked concerning the worlds, know that God has worlds without end, infinite beyond comprehension, and no one encompasses them except His All-Knowing, All-Wise Self. Reflect on sleep, for it is a great sign among people if they were to ponder. For example, you see something in your sleep at night, and you find it exactly as you saw it after a year, or two, or more, or less. Even though the world in which you saw what you saw in your sleep is not the same as the world you are in, what you saw in your sleep must exist in this world at the time you saw it in your sleep, and you are among the witnesses.
>
> Moreover, you see something that did not exist in the world, yet it appears afterward. This confirms that the world in which you saw what you saw is another world that has neither a beginning nor an end. If you say that this world is in your mind and is balanced within it by a command from an All-Mighty, All-Powerful source, this is true. And if you say that the spirit, when it is detached from attachments during sleep, is directed by God into a world that is concealed within the mystery of this world, this is also true.
>
> Indeed, God has world after world and creation after creation, and in each world, He has ordained what none can enumerate except His All-Accounting, All-Knowing Self. Reflect on what We have cast upon you so that you may understand the intention of your Lord and the Lord of all worlds. Within it lies a treasure of the mysteries of wisdom, and We have not elaborated on it due to the grief that has overwhelmed Me from those who were created by My word, if you are among those who hear.

Baha'u'llah says God reigns over all worlds.[^belief-in-the-worlds-1] With the Tablet to Vafa above, we can understand these worlds are infinite in number. Some may view worlds as being planets, but the usage suggests entities such as the universe or plane of existence. Dreams may not be an actual world, but are a sign of these various worlds. There are various theories which seem to address this type of reality, such as multiverses and quantum entanglement. I personally find quantum entanglement an interesting theory, as it expresses the interconnectedness of particles at great distances. Distances merely vary according to perspective. A small distance for a person might seem like a magnificent journey for a snail, and a small distance for a snail may seem like a magnificent journey for a tree. To a ray of light, all distances will seem to be the same. The key is no matter the distance, a cause with one particle can have effect on another. What if this were applied to worlds which are infinite in number?

[^belief-in-the-worlds-1]: Kitab-i-Aqdas Verse #39

This leads to an infinite number of potentialities. As Baha'u'llah discusses the existence of spiritual worlds that cannot be expressed by words nor pointed to by signs,[^belief-in-the-worlds-2] these worlds could exist in the same location as us but on a different plane of existence. They could also exist other locations which we sometimes pass through as Earth is on its own celestial journey, rotating around a Sun which rotates around the center of the Milky Way Galaxy, which rotates around the center of the universe, which might rotate around something else. We are never in the same spot we once were and most likely, never be in that exact same spot ever again. Our physical world is called the lesser world.[^belief-in-the-worlds-3] There is also a greater world.[^belief-in-the-worlds-4] In the writings of Baha'u'llah, the greater world seems to represent the very structure of existence itself. It's a vast spiritual reality which includes all divine realms.

[^belief-in-the-worlds-2]: Kitab-i-Aqdas Verse #116

[^belief-in-the-worlds-3]: Kitab-i-Aqdas Verse #55

[^belief-in-the-worlds-4]: Kitab-i-Aqdas Verse #55

### Kingdoms Within the Worlds

The Kingdom of Names bears witness God desires to rule over our hearts.[^belief-in-the-worlds-5] This Kingdom of Names is manifested in all worlds, spiritual and lesser. In the lesser world we may be aware of this Kingdom through the various signs, just as we were in learning about God. Every name and attribute is manifested from this Kingdom, and every name and attribute returns to this Kingdom.[^belief-in-the-worlds-6] It could also be possible some of these spiritual worlds solely manifest a single Name. Imagine the possibility of a particular day, we happen to pass through a spiritual world which reflects the name Just. We could be working on some task and suddenly come to a realization about a separate matter which seemed unjust or unfair. This realization leads to an inspired solution. Could this inspiration have come solely from our own imagination? Or could this inspiration actually have come from God and the Kingdom of Justice in a greater world? The Kingdom of the Lord[^belief-in-the-worlds-7] exists within all worlds. This kingdom represents God's sovereignty, one of the names of God. There is also the Kingdom of Command[^belief-in-the-worlds-8], representing God's names of commander, ordainer, and fulfiller.

[^belief-in-the-worlds-5]: Kitab-i-Aqdas Verse #83

[^belief-in-the-worlds-6]: Tafsir-i-Hu (Interpretation of the Name He)

[^belief-in-the-worlds-7]: Kitab-i-Aqdas Verse #79

[^belief-in-the-worlds-8]: Kitab-i-Aqdas Verse #91

### Cities and Schools Within the Kingdoms

These Kingdoms have cities of names where the Concourse on High and other dwellers exist.[^belief-in-the-worlds-9] If the worlds of God are countless, and God encompasses all names, it would also stand to reason these cities could also be infinite in number. Many scriptures refer to various cities in the worlds of God. Many Christians are familiar with the concept of Zion or the New Jerusalem. Hindus mention many celestial cities such as Amaravati and Dwarka, the birthplace of Lord Krishna.

[^belief-in-the-worlds-9]: Kitab-i-Aqdas Verse #132

These cities can also represent various stages of the maturation of the soul, such as the City of Love and Rapture.[^belief-in-the-worlds-10] Aiding this development are schools within these cities. The School of God is where the Tablets are revealed.[^belief-in-the-worlds-11] The School of God predates the creation of the Earth and heavens[^belief-in-the-worlds-12] and encompasses all the knowledge God the All-Knowing has. As we experienced in the chapter "Belief in God," belief in the knowledge of God is essential to belief in God the Creator. The Tablet may not necessarily be what is revealed in revelation, but what is revealed within the soul's personal journey. The School of God is something we could think of as a greater institute which itself has branches. These branches can focus on being sources of knowledge teaching a soul a particular value a soul can develop to progress along the divine names and attributes. The Kitab-i-Aqdas mentions the School of Detachment and the School of Meanings and Exposition while the Kitab-i-Badi mentions the School of Knowledge.

[^belief-in-the-worlds-10]: Gems of Divine Mysteries

[^belief-in-the-worlds-11]: Kitab-i-Aqdas Verse #176

[^belief-in-the-worlds-12]: Kitab-i-Aqdas Verse #177

Imagine the various combinations which could exist within these schools, cities, and kingdoms. Say you enter the School of Servitude, either here in the lesser world by chance, through meditation, or through a glimpse through one of the greater spiritual worlds of God. This School may help teach virtues such as humility or the fear of God. These lessons within the School of Servitude may help you enter the City of Submission which is when the soul is ready to surrender to God's Will. This School helps refine the soul and prepares it to reflect potential names such as the Almighty or the Lord of Lords. Eventually in Part 2 of this book regarding the relationship with God, I will present up to 39 virtues identified within the Kitab-i-Aqdas.

## The Soul's Purpose Within These Worlds

Belief in the worlds of God is essential to those who believe they have a soul. The purpose of the soul is to find pathways beyond the lesser world, even if at first it is merely just glimpses into the greater world. The Bayan says the soul progresses degree by degree, especially those who ponder upon the realm of the infinite.[^belief-in-the-worlds-13] As the soul is designed to reflect the divine names of God, the greater worlds manifest the divine names more purely than in the lesser world. The soul though, even when bound by the temple of the body, is able to experience the greater world. Think in a sense nirvana as taught by Buddha. For a soul not seeking, they may consider an outcome or event to be a matter of destiny or fate. However, for a seeking soul who reflects upon the spiritual realities, they may see an event or outcome as a reflection of a City of God, a Kingdom of God, a manifestation of a Name, and something guided by the divine hand.

[^belief-in-the-worlds-13]: Persian Bayan Vahid 2, Gate 12

The eventual destination is Heaven. Heaven is often used in the Kitab-i-Aqdas as a spiritual world itself, designating both a source of blessings and a destination for the soul. This paradise also reflects the names and attributes of God, such as the Heaven of Bounty[^belief-in-the-worlds-14] and Heaven of Revelation.[^belief-in-the-worlds-15] Baha'u'llah says "Paradise, it is a reality beyond doubt, and today in this world, it is my Love and My pleasure. Whoever attains it, God will assist them in this world, and after death, He will admit them into a Paradise whose expanse is like that of the heavens and the earth."[^belief-in-the-worlds-16] Paradise is also "my Love, your heavenly home, reunion with me."[^belief-in-the-worlds-17] The purpose of the soul is reunion with God in the heavenly paradise.

[^belief-in-the-worlds-14]: Kitab-i-Aqdas Verse #55

[^belief-in-the-worlds-15]: Kitab-i-Aqdas Verses #64 and #105

[^belief-in-the-worlds-16]: Suriy-i-Vafa

[^belief-in-the-worlds-17]: The Hidden Words of Arabic #6

A person who is a seeker and goes on a journey similar to that as described by Baha'u'llah in the Seven Valleys can attain heaven even while on earth. It is the condition of the soul which is near to God. The beautiful thing which I personally love with this cosmology is even if I do not attain this station now, I will forever have opportunities after my body gives way. The condition of being distant from God, also known as Hell, is not a condition which lasts forever. I would highly recommend reading the Bayan's Vahid 2, Gate 16 for a wonderful sermon about paradise and hell.

The Kitab-i-Aqdas does teach a powerful tool a person can use to elevate their own soul and that of others, reciting the Words of God in a melodious tone.[^belief-in-the-worlds-18] This practice mimics the melodies which come from the greater worlds. Baha'u'llah often describes these melodies as from the "nightingales of the Supreme Paradise."[^belief-in-the-worlds-19] It can also be the Words of God, no matter who sings them, are also heaven.

[^belief-in-the-worlds-18]: Kitab-i-Aqdas Verses #116, #150, #160

[^belief-in-the-worlds-19]: The Words of Paradise

## Inhabitants of the Greater Worlds

Earlier in this chapter the Celestial Concourse was mentioned. A concourse is a meeting place or a location where multiple paths merge. This could be similar to a convention center, transportation station, hotel, mall, or other places such as this. The Concourse on High would be the grouping of those who dwell in the greater worlds. They are inhabitants of the Eternal City.[^belief-in-the-worlds-20] These are the souls who have achieved the exaltation of paradise, of heaven, and of nearness to God. These souls wail when God restrains any knowledge, even for a moment, and they tremble and sway when He releases the knowledge.[^belief-in-the-worlds-21] They lament the fire of hatred[^belief-in-the-worlds-22] and have submitted to the Cause of God.[^belief-in-the-worlds-23]

[^belief-in-the-worlds-20]: The Persian Hidden Words #71

[^belief-in-the-worlds-21]: BH00230

[^belief-in-the-worlds-22]: Kitab-i-Aqdas Verse #89

[^belief-in-the-worlds-23]: Kitab-i-Aqdas Verse #132

The Hosts of the Celestial realm and the nearest angels will aid anyone who rises to assist the Cause of God.[^belief-in-the-worlds-24] Angels are celestial beings whose purpose is to do God's will. They send His Tablets[^belief-in-the-worlds-25] and are able to traverse the greater worlds into our lesser world.[^belief-in-the-worlds-26] They will announce with a trumpet the arrival of a Messenger with a Message.[^belief-in-the-worlds-27] Angels also announce the death of a person, bring about wrath and punishment for a soul which had not progressed.[^belief-in-the-worlds-28]

[^belief-in-the-worlds-24]: Kitab-i-Aqdas Verse #53

[^belief-in-the-worlds-25]: Surah of Our Name The Messenger

[^belief-in-the-worlds-26]: Tablet of the Birth

[^belief-in-the-worlds-27]: Kitab-i-Iqan (Book of Certitude)

[^belief-in-the-worlds-28]: Surah Fu'ad

A soul which has been purified can achieve a station as angels.[^belief-in-the-worlds-29] I do not believe a human soul has the ability to become an angel, but metaphorically they can have a station similar to an angel, serving many of the same purposes. These purified souls, which could include loved ones from here on Earth who have passed away, might be offering aid and assistance. Belief in these inhabitants helps us understand we are not alone on our spiritual journeys. God has devoted an incredible amount of energy within creation to help us and sustain us through our good times and bad times.

[^belief-in-the-worlds-29]: Kitab-i-Iqan (The Book of Certitude)

As you can see, there is this unity between all of creation. What we do today has effect with the beings of the greater worlds, not just here in our physical world. What happens in the greater worlds can also have effect here in our lesser world. We are all entangled. The best way to understand this interwoven unity, this entanglement, is through the Sidrat al-Muntaha.

## Sidrat al-Muntaha

The Sidrat al-Muntaha means the Tree of the Farthest Extent. It is also known as the Divine Lote Tree. If we imagine we are looking out from a high mountain or maybe on a beach looking out to the ocean, we can see where the land and the sky meet. No matter how far on Earth we journey, we could never discover the physical point where the Earth and sky actually meet. The Sidrat al-Muntaha represents the point where the lesser world and the greater worlds meet. It is not something you can physically reach, but it is the furthest extent our terrestial knowledge will get us before we need our spiritual knowledge to progress. The Kitab-i-Aqdas says "the Lote-Tree of the farthest limit proclaims: 'There is no God but Me'"[^belief-in-the-worlds-30]

[^belief-in-the-worlds-30]: Kitab-i-Aqdas Verse #100

The Sidrat al-Muntaha can call out and proclaim. It has Branches which provide shade and salvation.[^belief-in-the-worlds-31] As this is within the horizon where the worlds meet, it is also the point where light appears and disappears. The Divine Lote-Tree is the place of Dawn for the Day of Resurrection. The Breaker of Dawn, who speaks between the heavens and the earth[^belief-in-the-worlds-32] is also a celestial being often known as the Holy Spirit, or in Baha'u'llah's words the Holy Maiden. Baha'u'llah describes her this way:

[^belief-in-the-worlds-31]: The Tablet of the Branch

[^belief-in-the-worlds-32]: Kitab-i-Aqdas Verse #117

> I heard the most beautiful, the sweetest voice above my head. When I turned, I saw a maiden, the mention of my Lord’s name suspended in the air, aligned with the sun’s head, and I saw her rejoicing in herself. As if the embroidery of pleasure appears from her face and the light of mercy declares from her cheek. She was speaking between the heavens and the earth with a call that attracts hearts and minds and gives all my limbs, both outward and inward, the good news that my soul was rejoiced with, and honored servants rejoiced from it.[^belief-in-the-worlds-33]

[^belief-in-the-worlds-33]: Suriy-i-Haykal (Surah of the Temple)

What is spoken from the Sidrat al-Muntaha is the Mother Book, which is the hidden treasure.[^belief-in-the-worlds-34] The Mother Book includes everything spoken by God, and things which people are not ready to hear. It contains all knowledge and also manifests all of God's names and attributes.

[^belief-in-the-worlds-34]: Kitab-i-Aqdas Verse #103

The Holy Spirit also appears from the Sidrat al-Muntaha. Much like the Holy Maiden, revelation appears from them. While the Holy Maiden may be a personal apparition for Baha'u'llah, the Holy Spirit has descended from Heaven to animate the missions of those such as Jesus Christ. The Holy Spirit has its own language.[^belief-in-the-worlds-35] The Holy Spirit can also act as an intermediary between the Manifestations of God and us, or between God and us. It calls from the Kingdom of God[^belief-in-the-worlds-36] and animates and inspires life within the soul, even if the souls seems inert or dead. The Holy Spirit is a source of grace.[^belief-in-the-worlds-37]

[^belief-in-the-worlds-35]: Suriy-i-Haykal (Surah of the Temple)

[^belief-in-the-worlds-36]: Kitab-i-Aqdas Verse #80

[^belief-in-the-worlds-37]: The Persian Hidden Words #58

Belief in the Sidrat al-Muntaha is important as it helps a person understand there are pathways for divine assistance available to us. These can come when we need it, even if we don't seek this assistance. These can come if we choose to approach the Sidrat al-Muntaha on our own accord. It represents a constant hope for the soul and constant pathway for God's names and attributes to have real effect in our lives.

## Summary

Belief in the worlds of God, and all which exists within them, is vital to the progression of the soul. These realms and entities are not abstractions and are signs of God's names and attributes and help manifest these realities in a way which can elevate the soul, whose purpose is to be near to God in the condition of paradise. This also demonstrate we are not alone in our journey. Sometimes life here in this lesser world can be difficult. There is suffering, pain, and seemingly insurmountable challenges. All of these experiences are real. Are these experiences supposed to keep us down, or help us rise to greater heights?

We are never alone as long as we believe we are not alone. Belief in angels as real entities, not merely as symbols, is important. Belief those prior to us who loved us may be offering a helping hand within the worlds of God is deeply heartfelt. Belief in the Holy Spirit as a real entity who animates life within the soul inspires living with purpose. Belief that the worlds of God are infinite ensures our imagination can be alive, never bound by our primary senses. Infinite worlds equal infinite possibilities. The spiritual journey unfolds endlessly across dimensions unseen. This is where unity comes from, the manifestation of God's Oneness. It may not necessarily be the manifestation of sameness, but through a real understanding every soul, every world, every being, and all of creation are woven together like a divine tapestry.

If any of this is ever in doubt, be open to dreaming. Be willing to remember those dreams. The Kitab-i-Iqan and books like the Surah of Joseph in the Qur'an, or even the Ahsan al-Qasas by the Bab (The Best of Stories) which further explains the Surah of Joseph, testify to the value and symbology which are embedded within dreams. I can personally testify I first started this path of my journey to the Bab and Baha'u'llah due to a series of dreams I experienced. Dream big. Be imaginative. Your soul is ready to for an amazing journey.

The next chapter will discuss belief in the Day of God, also known as the Day of Resurrection.

{{< pagebreak >}}
