---
title: "Belief in the Manifestation of God"
---

## The Station of the Manifestation

In Chapter 1, we explored the various names and attributes of God to help understand what belief in God can encompass. The second group is Manifestation. The ability for God to manifest Himself to His creation is fundamental for us. Manifestation turns the inaccessible and subtle into more tangible and easier to discern aspects of reality. One of the ways God manifests Himself is through the human flesh. While this flesh is bound by the material world, the soul within it reflects divinity in such a way the other names and attributes of God also appear. While the historical terms of prophet, messenger, avatar, or apostle help us understand aspects of this divinity and purpose, the Manifestation serves as the living bridge between our human soul and divine reality.

We also explored in Chapter 3 the symbol of the Sidrat al-Muntaha, the tree of the farthest extent. The Manifestation of God serves as the Dawning Place, a title used regularly throughout the Kitab-i-Aqdas. The Manifestation is the Dawning Place of Revelation, of the Light of Divinity, of God's Most Excellent Names, of Grandeur, of God's Most Radiant Cause, and of Oneness. This Dawn itself marks the fulfillment of the Day of Resurrection. "By Him the Hour has come."[^belief-in-the-manifestation-of-god-1] He appears "in the Most Glorious attire"[^belief-in-the-manifestation-of-god-2] as if He were a Monarch. The Manifestation is also the means by which the human soul is able to understand God's will, purpose, and those other names and attributes more fully. "Whoever has turned to Me has turned to the Worshiped One."[^belief-in-the-manifestation-of-god-3] The Manifestation is the focal point for the devotional life for God, much like the Qiblih of Islam or the Temple of Judaism. Thus, all Manifestations of God are the Sidrat al-Muntaha, with each being a branch of this divine tree.

[^belief-in-the-manifestation-of-god-1]: Kitab-i-Aqdas Verse #81

[^belief-in-the-manifestation-of-god-2]: Kitab-i-Aqdas Verse #82

[^belief-in-the-manifestation-of-god-3]: Kitab-i-Aqdas Verse #131

This whole purpose of the Manifestation is entirely for our soul. The belief in the soul, as described in Chapter 2, requires belief in the Manifestation as the primary means of progress towards God. They serve not only as the Dawn for the worlds of God, but they also serve as the Dawn of the transcendence of the soul as it prepares to navigate the spiritual worlds of God. We express this belief by recognizing the Dawning Place of Grandeur, their exalted nature over everything else on Earth, and their high spiritual capacity and fragrance. We express this belief by recognizing their Revelation, which is the Word of God, the Command and Counsel which guides and organizes all with justice and mercy. We practice this through submission and love, in fear and in awe, in faithfulness and good deeds.

This station of Manifestation has been fulfilled by many throughout history. Baha'u'llah is the most recent of these Manifestations of God who has brought forth Revelation as their divinely ordained mission. Prior to Baha'u'llah was the Bab, who was also known as the Primal Point. There have been countless others throughout history. The Bab Himself had said in the Persian Bayan, "The names and attributes are manifestations of the multiplicity of that primal unity. Reflect upon the verbal letters of the Bayán: all multiplicity originates from the first unity, even if it extends infinitely. And in the multiplicity of the universal manifestations, there arises a strength in the manifestation surpassing that of the primal unity. Yet, all things are realized through Him, and all return to Him, just as they originate from Him." Even if we look at traditions which seem polytheistic, they are not. All are Manifestations of God, expressions of God's attributes according to the needs and cultures of their time.

Belief in Baha'u'llah is belief in all the prior Manifestations of God, belief their words and cause were true, but also belief that the prior Manifestation's teachings are now superceded by Baha'u'llah's revelation. It is the dawn of a new day with a new command, which will serve us until the dawn of the next day with a next Manifestation. The next sections of this chapter will go more fully into the titles, powers, and roles of the Manifestation of God and our relationship with Him.

## Baha'u'llah

In Baha'u'llah's writings, some Manifestations are referred to by certain titles. For example, Jesus is often referred to as the Spirit[^belief-in-the-manifestation-of-god-4] and Muhammad as the Messenger of God.[^belief-in-the-manifestation-of-god-5] In the Bayan, the Bab had said everything in the Bayan is for He Whom God Shall Make Manifest (HWGSMM), a title used at least 240 times in the Bayan. Baha'u'llah refers to this title in the Kitab-i-Aqdas in verse #137. This helps signal to the Babi community the station Baha'u'llah is claiming. HWGSMM was said to be one to complete the Bayan.[^belief-in-the-manifestation-of-god-6] The Kitab-i-Aqdas serves as the completion of the Bayan, with some laws abrogated and some laws confirmed. As we go through this book, we will sometimes refer to these changes or instances where a command from the Bayan might still apply. Understand though, that while the Kitab-i-Aqdas also refers to the Bab as Baha'u'llah's Herald,[^belief-in-the-manifestation-of-god-7] the Bab was completely a Manifestation of God. Baha'u'llah is also a Herald for a future Manifestation of God who will come no earlier than 2873AD (1029 Badi Calendar).[^belief-in-the-manifestation-of-god-8]

[^belief-in-the-manifestation-of-god-4]: Kitab-i-Aqdas Verse #80

[^belief-in-the-manifestation-of-god-5]: The Suriy-i-Rais (Surah to the Chief)

[^belief-in-the-manifestation-of-god-6]: The Testament of the Bab to Subh-i-Azal

[^belief-in-the-manifestation-of-god-7]: Kitab-i-Aqdas Verse #137

[^belief-in-the-manifestation-of-god-8]: Kitab-i-Aqdas Verse #37

Baha'u'llah was often referred to as the Greatest Name.[^belief-in-the-manifestation-of-god-9] The Greatest Name is reference to various Muslim traditions. In one way, God can elevate any of His names to be the greatest, as ultimately all names come from the word "One". In this dispensation, the Greatest Name is Baha, which means Glory. Much like how Jesus was given the name Son, these names are used to demonstrate a primary purpose in the mission of the Manifesation. The Gospel of John says the gospel exists so all may become sons of God, so thus Jesus's mission was to teach Sonship of God the Father. Simultaneously, Krishna means all-attractive and His mission was to demonstrate what true devotion to God and knowledge of the true Self, which are all manifestations of Beauty and Love. The purpose of Baha'u'llah's mission then, is for us to embody and believe in the quality of Glory. The revelation is to demonstrate in every way the exaltation of God, His Majesty over all, and only He is the Infallible. It is also our purpose to reflect this Glory to the best of our abilities, which helps make the world around us more beautiful, more magnificent, and more illustrious. This purpose teaches us we all deserve these attributes and are also able to manifest them, if we so believe. This Glory reigns supreme over all the worlds.[^belief-in-the-manifestation-of-god-10]

[^belief-in-the-manifestation-of-god-9]: Kitab-i-Aqdas Verse #51

[^belief-in-the-manifestation-of-god-10]: Kitab-i-Aqdas Verse #127

The Kitab-i-Aqdas does not go too deeply into the biography of Baha'u'llah, which may matter to some. Belief in Baha'u'llah as the Manifestation of God does not require knowledge of the biography, but there are some aspects about Him which are mentioned. The Book says He is unlettered,[^belief-in-the-manifestation-of-god-11] saying "I have not entered schools, nor have I studied scholarly works." Despite this, He is unmatched in the fields of mystical insight and knowledge and none can keep up with Him in the course of wisdom and expression.[^belief-in-the-manifestation-of-god-12] He Himself had entered various Schools of God.[^belief-in-the-manifestation-of-god-13] Baha'u'llah first had His epiphany of station while within the prison called the Black Pit of Tehran in the year 1852 (8 BE). He says this in the Surih-i-Haykal:

[^belief-in-the-manifestation-of-god-11]: Kitab-i-Aqdas Verse #104

[^belief-in-the-manifestation-of-god-12]: Kitab-i-Aqdas Verse #101

[^belief-in-the-manifestation-of-god-13]: Kitab-i-Aqdas Verses #175 & 176

> So when I saw myself at the pole of affliction, I heard the most beautiful, the sweetest voice above my head. When I turned, I saw a maiden, the mention of my Lord’s name suspended in the air, aligned with the sun’s head, and I saw her rejoicing in herself. As if the embroidery of pleasure appears from her face and the light of mercy declares from her cheek. She was speaking between the heavens and the earth with a call that attracts hearts and minds and gives all my limbs, both outward and inward, the good news that my soul was rejoiced with, and honored servants rejoiced from it.
>
> She pointed with her finger at my head and addressed those in the heavens and the earth, by God, this is the beloved of the worlds, but you do not understand. This is the beauty of God among you and His authority within you, if you indeed know. This is the secret of God and His treasure and the command of God and His dignity for those in the dominion of command and creation, if you indeed comprehend. Indeed, this is the one whom those in the realm of permanence long to meet, then those who have settled behind the most splendid pavilion, but you turn away from his beauty.

In Baghdad, He revealed His mission during the festival of Ridván in 1863 (19 BE), "when We manifested to those in existence with Our most beautiful names and highest attributes."[^belief-in-the-manifestation-of-god-14] This mission continued until His passing in 1892 in Akka. Both Baghdad and Akka were part of the Ottamon Empire in these days. While in Akka, Baha'u'llah was in the Most Great Prison, where the Kitab-i-Aqdas itself was revealed.[^belief-in-the-manifestation-of-god-15] Despite being a prisoner of the Persian and Ottomon Empires for most of this 40 year period as a Manifestation of God, He says His love is able to burn away veils[^belief-in-the-manifestation-of-god-16] which inhibit one's ability to fully believe in God. This love and imprisonment serves one major purpose.

[^belief-in-the-manifestation-of-god-14]: Kitab-i-Aqdas Verse #75

[^belief-in-the-manifestation-of-god-15]: Kitab-i-Aqdas Verse #132

[^belief-in-the-manifestation-of-god-16]: Kitab-i-Aqdas Verse #132

> Hasten to what you were promised in the Books of God, and do not follow the ways of the ignorant. My body has been imprisoned for the liberation of your souls. Turn towards the Face, and do not follow every tyrant and obstinate one. He accepted the greatest humiliation for your honor.[^belief-in-the-manifestation-of-god-17]

[^belief-in-the-manifestation-of-god-17]: The Lawh-i-Aqdas (Most Holy Tablet)

Baha'u'llah's mission is the freedom of our souls from oppression. It might seem somewhat similar to the liberation theology of the 1960's, which used Christian doctrine as inspirations of revolution.

You will see the rest of this book outlines how the Kitab-i-Aqdas fulfills this mission through the commands and revelation of Glory. Every law, counsel, exhortation, and theological ruling should be considered from the perspective of this mission, the mission born of the love from God for all of us.

## How Baha'u'llah Fulfills His Mission

The Kitab-i-Aqdas is ripe with various symbols and expressions of the way Baha'u'llah fulfills His Mission for us. These titles include the Sun, the Pen, the Shepherd, the Sea, the Master, the Remembrance, the Temple, the Judge, the Chief, the Reminder, the Tongue, the Book, and We. These titles are often used in conjunction with other descriptions, but as you can see, these titles are encompassing of many roles and duties. All of these roles are framed within the name Glorious, and Baha'u'llah's roles should be considered with respect of this exalted station.

Belief in Baha'u'llah as the Manifestation of God for our age does not mean to merely view Him as a philosopher or ethical reformer. He should not be viewed as a Unitarian where all paths currently lead to the same destination. Belief in Baha'u'llah as the Manifestation of God for our age means to view Him as more glorious than any person. This station lasts until the Day of His Revelation sets and a new Manifestation of God appears to fulfill the next Covenant. Every word, every letter, every breath which came from Baha'u'llah is the pathway for freedom.

## Conclusion of Part 1

This concludes the key components of belief which are vital to understanding the Kitab-i-Aqdas and building distinctive communities of glory. I understand these beliefs in their entirety will not be automatic. It would be inauthentic of myself to say my belief today was exactly the same as my belief yesterday. My belief will also change tomorrow as I learn more about myself. I will even admit as I have written this first part, I have expressed things I did not even realize I believed in. Belief is always in motion. Much like when quantum entanglement was discussed, as soon as we make an observation of a thing, the nature of that thing has already changed in some shape, condition, or position.

Part 2 will focus on ways the Kitab-i-Aqdas guides us to have a devotional relationship with God. This devotional relationship will not automatically cause you to believe in everything immediately, but it will provide pathways to unveiling the Subtle and giving purpose to your soul's journey towards true freedom. These practices will also help develop key values we can use in our everyday life. These values not only inform our beliefs, but also our actions, words, and perspectives towards the diversity of others who we experience each passing day.

{{< pagebreak >}}
