---
title: "Belief in Angels"
---

## Hosts of the Celestial Realm

Will aid anyone who rises to assist His Cause.

Remember those who abandon oppression and wrongdoing and embrace piety.

Will not get near those who have stained garments during prayer.

Hastened in longing to meet Him (Baha'u'llah)

## Concourse on High

Lamented the fire of hatred from Istanbul.

Has submitted to the Cause of God.

## Concourse of Creation

O concourse of creation! Hear the call of the Lord of Names. He calls you from His Most Great Prison: Truly, there is no God but Me, the Almighty, the Majestic, the Subduer, the Exalted, the All-Knowing, the All-Wise. There is no God but Him, the Almighty over all the worlds. If He wills, He can seize the world with a single word from His presence. Beware that you do not hesitate in this Cause, to which the Concourse on High and the dwellers in the cities of names have submitted. Fear God and do not be of the veiled. Burn away the veils with the fire of My love, and the clouds of glory with this Name by which We have subdued all the worlds.

## Those Who Circle Around the Exalted Throne

Lamented the fire of hatred from Istanbul

## Angels

A company of nearest angels will aid anyone who rises to assist His cause.

## Those Who Dwell in this Station

Remember those who abandon oppression and wrongdoing and embrace piety.

## The Breaker of Dawn (Maybe Holy Maiden)

The Tablets have been adorned with the seal of the Breaker of the Dawn, who speaks between the heavens and the earth.
