---
title: "The Constructive Social Life"
---

The next two chapters will move from the private self to the social life. This will focus on interactions with all people, regardless of their status in your life. This chapter will discuss the constructive social life which is framed as the Cause of God. These are a framework of positive actions designed to be the foundations and instruments of change within our communities.

Throughout the book, there have been allusions to our responsibilities towards others. The names of God shed light on the potential perspectives we can strive to. The soul and human station teaches us the special and noble character all people are capable of. The spiritual worlds allows us to creatively imagine the unique journeys all will take. The urgency of the Day of Resurrection ensures we act with the best interest of all. The command through the Manifestation of God inspires us with what is best in a world which sorely needs our best. The spiritual practices refine our constellation of virtues so we are increasingly an example to whomever we cross paths with. We established foundational rights all people deserve, regardless of any status. We also ensured we are aware of responsibilities of maturity while burning the veils of illusions and desires we have privately held.

All of the prior rights and responsibilities expressed so far in Part 3 still apply in this chapter. What follows builds upon this foundation.

## The Cause of God

Throughout the book, we have several times mentioned the Cause of God in association to Huquq'u'llah, reflection, and even the spiritual worlds. My personal opinion is the Cause of God fully manifests itself in the constructive social life of a person, where we go beyond the individual and consider the community. To lead this concept, Kitab-i-Aqdas #58 presents a great framework to express the Cause of God and how to view community.

> Beware lest the affairs of the self and desire cause division among you. Be like the fingers of one hand and the limbs of one body. Thus does the Pen of Revelation counsel you, if you are of those who believe with certainty.

#58 largely explains itself, but I do want to add the extra visual. What happens when a finger is injured, weak, or severed? The hand might still function but not as effectively as before. The same is true about the limbs of a body. It means we must make utmost care to ensure each aspect is strong, healthy, and purposeful in function. To do this, Baha'u'llah offers various guidance associated with the Cause of God.

All believers have the responsibility to exalt God's Word.[^constructive-social-life-1] This also places other words from other sources as secondary. This does not mean to exclude other words, but by keeping God's Word in its rightful station, all fingers can be mindful of what the Cause is. All people have a right to know what the Cause of God is and to know God's Word as exalted, even if they do not believe it. They deserve the opportunity to know. To clarify what God's Word is, Baha'u'llah says to use this Book only[^constructive-social-life-2] as prior scripture avails nothing today. While we acknowledge the truth of scriptures past, we must be completely understand they are relevant today as historical context, not sources of God's living will. This will remain true until the next Manifestation of God appears when the Kitab-i-Aqdas is replaced by a new Book.

[^constructive-social-life-1]: Kitab-i-Aqdas #38

[^constructive-social-life-2]: Kitab-i-Aqdas #168

We have responsibilities to associate[^constructive-social-life-3] and consort[^constructive-social-life-4] with the followers of other religions in a spirit of friendliness and fellowship. The followers of other religions have a right to be associated with, without being excluded nor shunned on the basis of belief. This allows us to proclaim[^constructive-social-life-5] and assist[^constructive-social-life-6] the Cause in a positive and healthy way. To help with proclamation, Baha'u'llah also advises us to learn different languages[^constructive-social-life-7] so we can communicate with different people. This is not a requirement, though. We should serve the Cause in all conditions.[^constructive-social-life-8] We are promised God strengthens us and He is with us and will aid us. With this promise, there is no need to hesitate in serving this Cause[^constructive-social-life-9] or to let disbelievers' sorrow to overcome us.[^constructive-social-life-10] With God's Word being exalted, there is no reason to dispute about God and His Cause[^constructive-social-life-11] even if there are interpretive differences and various understandings. We have right to be free from disputes about God and His Cause. The fear of God will help to keep veils away[^constructive-social-life-12] which can lead to disputes, much like they helped with the prior chapter's illusions and desires. God's love burns away those veils, a love which is the foundation of the friendliness and fellowship to show others.

[^constructive-social-life-3]: Kitab-i-Aqdas #75

[^constructive-social-life-4]: Kitab-i-Aqdas #144

[^constructive-social-life-5]: Kitab-i-Aqdas #75

[^constructive-social-life-6]: Kitab-i-Aqdas #38

[^constructive-social-life-7]: Kitab-i-Aqdas #118

[^constructive-social-life-8]: Kitab-i-Aqdas #74

[^constructive-social-life-9]: Kitab-i-Aqdas #132

[^constructive-social-life-10]: Kitab-i-Aqdas #35

[^constructive-social-life-11]: Kitab-i-Aqdas #177

[^constructive-social-life-12]: Kitab-i-Aqdas #132

We have a responsibility to support His chosen ones.[^constructive-social-life-13] Throughout the revelation, Baha'u'llah refers to Manifestations of God as Chosen, but He also refers to others as chosen. Baha'u'llah in the Kitab-i-Badi offers an allegory of who chosen ones are. Those who rejected the idol of the golden calf, an illusion to the days of Moses, were chosen. Much like how the Hebrew people who believed in God and Moses were the Chosen Ones of God in those early days of Israel, Baha'u'llah affirms this criteria for today. In the Surah of the Temple, he says these chosen ones end up in God's Kingdom. In the Kitab-i-Aqdas, He says these chosen ones elevate His Word (exalting) and are the stars of heaven. To support one of these people could be in a variety of ways. It could be through prayer, financial assistance, giving food and other provisions, printing a book, or other logistical need. We have a responsibility to support them. Baha'u'llah regularly used Huquq'u'llah to support His chosen ones. We must be careful, though, from promoting ourselves as chosen.

[^constructive-social-life-13]: Kitab-i-Aqdas #117

For example, I have no right to claim I am chosen by God or Baha'u'llah. But, maybe we observe someone who exalts God's Word, is friendly and kind to people of varying religions, is learning languages to travel to a new land to proclaim the Cause, and exemplify this other criteria. We have a responsibility to support them. My personal belief is any person who says they are chosen by God or Baha'u'llah most likely is exalting themselves and should be approached cautiously. Now if a community feels I am chosen, they have every right to support me. Even then, all chosen ones are still fingers of the hand and limbs of the body. Never should we exalt anyone chosen, just merely support them in the Cause and the Cause only.

### Community Building

Another purpose with the Cause of God is to ensure the development of our communities. The only guaranteed method of socioeconomic development which lifts up all fingers of a hand is through working together with shared or complimentary goals and roles. Baha'u'llah ties development as a responsibility for everyone.

Baha'u'llah says to build up the cities and lands of God[^constructive-social-life-14] then remember Him within them. This building up includes not only specific buildings of faith, but also the infrastructure to support the entire Cause. In the chapter "Honoring God" we learned how having an occupation is a requirement for those who are able to. Each business and supporting jobs must have their buildings, markets, and networks such as communications and transportation. Infrastructure must exist to support the right to provision, even if provision is governed by market pricing. This provision as stated in Chapter 14.7 includes environmental necessities. Every person has a right to socioeconomic development, and it is a responsibility of all believers. Other infrastructure would be focused on what is needed to fulfill the full spectrum of rights afforded to all.

[^constructive-social-life-14]: Kitab-i-Aqdas #160

Outside of the business sphere, we are also to build your own houses (dwellings) as perfectly as possible in the lands.[^constructive-social-life-15] This would include the outside and the inside such as furnishings. This interplays highly with the constellation of virtues, and like all of our rights, we must be mindful in how we express them. A house must not need to be extravagant to be as perfect as possible, but within the means you have, keep it as perfect as possible. Baha'u'llah also tells us to renew our furnishings after the passing of nineteen years.[^constructive-social-life-16] All people have a right to secure dignified housing.

[^constructive-social-life-15]: Kitab-i-Aqdas #31

[^constructive-social-life-16]: Kitab-i-Aqdas #151

On the religious side, the command to build Mashriq-ul-Adhkars in every city and village is a key component of the socioeconomic development of the lands. It is the right of every person to have access to one, even if they do not have a responsibility to enter if they have different religious practices. As every person has a right to belief, there should be no restrictions in allowing the people of other religions from building whatever places of worship and faith. Remember we are to be friendly and offer fellowship. Yet, all believers of Baha'u'llah have a responsibility to build Mashriq-ul-Adhkars.

The final aspect of the socioeconomic development of the lands are to build Houses of Justice in every city[^constructive-social-life-17] when believing individuals reach 9 or more. The Houses of Justice have clearly defined roles, functions, and funding which will be explained in its own chapter due to its uniqueness and importance. While being tied to religious revelation, these Houses of Justice exist as representatives for all who dwell on Earth[^constructive-social-life-18] regardless of which city they are in. The implication is every city should receive the benefits of a House of Justice within them. The individuals who arise to serve on the Houses of Justice do so to serve the Cause.[^constructive-social-life-19] Houses of Justice do not need to be built in villages, but there is no exclusion if there are the minimum 9 individuals.

[^constructive-social-life-17]: Kitab-i-Aqdas #30

[^constructive-social-life-18]: Kitab-i-Aqdas #30

[^constructive-social-life-19]: Lawh-i-Bisarat (Glad Tidings) - 13th Glad Tiding

The Cause of God cannot be in progress without any of these aspects of socioeconomic development. If one is missing or excluded, the limbs of the body of the community will have weakness. Perhaps they will grow unequally. The Cause of God is the pathway of liberation for all people. In order to ensure this pathway is truly beneficial for all in a community, Baha'u'llah enjoins specific responsibilities for all believers and rights for all people. The following section will briefly list the positive social actions required to support the Cause of God.

### Positive Social Actions

A responsibility to act with good deeds[^constructive-social-life-20] and a right to be free from bad deeds.

[^constructive-social-life-20]: Kitab-i-Aqdas #73

A responsibility to engage in activities which benefit yourself and others[^constructive-social-life-21] and a right to be free from harmful activities by others. Associated with this is a prohibition of idleness, the wasting of time without any meaningful activity. Sloth is also prohibited, which is an apathetic reaction to opportunities and duties. With this, we have a right from being forced into idleness.

[^constructive-social-life-21]: Kitab-i-Aqdas #33

A responsibility to provide for the poor and needy[^constructive-social-life-22] and a right to be free of poverty.

[^constructive-social-life-22]: Kitab-i-Aqdas #16

A responsibility to provide hospitality[^constructive-social-life-23] once per Bayani month.

[^constructive-social-life-23]: Kitab-i-Aqdas Verse 57

A responsibility to fulfill promises[^constructive-social-life-24] and a right for promises received to be fulfilled. Promises can be informal such as verbal agreements with friends or the proverbial pinky promise, or they can be formalized through contracts.

[^constructive-social-life-24]: Kitab-i-Aqdas #156

A responsibility to purify every disliked thing with water[^constructive-social-life-25] and a right to purified things. The layers of this could be garments, surfaces, buildings, and publicly shared spaces. As there is a prohibition on consuming intoxicants, as we purify things we should be careful in using chemicals which can act as toxins inside and outside the body.

[^constructive-social-life-25]: Kitab-i-Aqdas #74

A responsibility to respond with joy when invited to banquets and gatherings[^constructive-social-life-26] and a right to receive a response to such invitations. The response can be a no, but if it is a yes, the promise should be fulfilled. If the response is a joyless yes, consider making it a no.

[^constructive-social-life-26]: Kitab-i-Aqdas #156

A responsibility from being a plaything for the ignorant,[^constructive-social-life-27] a responsibility born from good manners. This can be associated with what we say, do, or present ourselves. All has a right from being considered as playthings.

[^constructive-social-life-27]: Kitab-i-Aqdas #159

A responsibility to seek knowledge for the recognition of the known[^constructive-social-life-28] and a right to seek knowledge. Relatedly we have a responsibility to read from sciences which benefit you[^constructive-social-life-29] with a right to be able to read these sciences. This could be rather expansive but would require discernment. In general, the pursuit of facts, the wisdom to use these facts to benefit yourself and others, and caution towards opinions which disguise facts and harms.

[^constructive-social-life-28]: Kitab-i-Aqdas #102

[^constructive-social-life-29]: Kitab-i-Aqdas #77

A responsibility to respond in kindness if angered.[^constructive-social-life-30] Note this is not a prohibition of anger, but a guidance to ensure anger does not end up betraying our constellation of virtues. There is a right to be responded to without anger.

[^constructive-social-life-30]: Kitab-i-Aqdas #153

A responsibilty to respond to being rebuked without rebuking. This can imply a prohibition on rebuking altogether. Instead, in the spirit of friendliness and kindness, consider using reminders, counsel, or advice. Baha'u'llah advises Napoleon III and the people of France to cover up mistakes instead of arguing.[^constructive-social-life-31] This does not mean hide injustice or the breaking of laws.

[^constructive-social-life-31]: The Suriy-i-Haykal 150 & 151

These sets of responsibilities and rights are the pivotal framework of a healthy social life no matter who we cross paths with. In a perfect world where everyone believed in and abided by the Kitab-i-Aqdas, these positive social actions would be enough to create heaven on Earth. Realistically this may never be the case. For example, a person may consider implementing what they consider to be good deeds, but do so without the beliefs of part 1, the spiritual practices of part 2, and without refining their private life. This is the essence of the very first paragraph of the Kitab-i-Aqdas, where Baha'u'llah says "whoever is deprived of it is indeed among the people of error, even if he performs every good deed." We should be careful from taking shortcuts.

In the event of shortcuts within this framework, Baha'u'llah introduced protections to help ensure the rights of all people. These are all clear prohibitions which set boundaries we should never cross in our social life. Most are non-punitive and some are punitive. These are the first laws of the Kitab-i-Aqdas which Baha'u'llah designed to be enforceable by a justice system which this book covers. The next chapter will discuss the protections for the social life.
