---
title: "Disbelievers"
---

## Qualities of Disbelievers

People of error

Like the ignorant masses

They hold onto their own conjectures and illusions.

Clung to their own principles instead of those of God

Sorrowful.

Seek prestige

Claim hidden knowledge.

Claim esoteric understanding

Denied what God has permitted

Borne ascetic hardships

Makes actions the partner of hopes.

Among the dead

Claims a share of the greatest infallibility

Causes corruption

Sinful

Far from the Source of Closeness.

Veiled from the source of knowledge

## Polytheistic

Turned to different Qiblih

## Deceived by Knowledge

Veiled from God's Name, the Self-Subsisting. See themselves as greater than Nimrod. They worship their own idols of desire.

## Wolves in Garments

Oppressors

## They are Asleep

If they were to awaken, they would hasten with their hearts towards God. Their sleep is caused by the intoxication of desire, in such a way they cannot see the Lord. They will awaken but not find anything of what they missed in the days of the Lord.

Glory of the Exalted Will Not Endure

The Ornaments of the Wealthy Will Not Endure

The Power of the Wicked Will Not Endure

## Distorts the Word of God

One who interprets what has been revealed from the heaven of Revelation and deviates from its outward meaning is among those who have distorted the exalted Word of God and is accounted as one of the losers in the clear Book.

Speaks contrary to what has been revealed in the Tablets

## Believes in Former Revelation

Intoxicated in the

## How to Act Towards Them

We should act in a way where their own sorrows do not overcome us.

## Humiliating Punishment

For those whose eyes have been intoxicated in the former and the latter.
