---
title: "Family Life"
---

## Treating Kindred

Show love and kindness to your kindred.

None have a right to the wealth of the people. Mention inheritance.

## Marriage

Marriage is enjoined upon us. Enjoined is an authoritative instruction or directive which implies it is either required or highly encouraged. The same word is used regarding prayer and fasting, which is usually interpreted to mean as they are required, pending acceptable exceptions.

### Purpose of Marriage

The purpose of marriage is to have at least one child, a child who will remember God.

### Monogamy or Bigamy

The man is allowed up to two wives. More than two wives is not allowed. The man who is content with one wife with ensure both of their tranquility. This implies there can be complicating issues with polygamy. The first ones I can think of could be jealousy or a fear from the wife that perhaps she is not good enough to completely satisfy her husband. Insecurity definitely impacts tranquility. This means monogamy is preferred, although it is not required.

There is no rule which explicitly expresses a limitation on the number of husbands she can have. However, in regards to the teachings Baha'u'llah offers in his letters to Shiraz, he unequivacally states women are equal to men. Perhaps then, this is also applies to marriage law although there is no evidence a Baha'i woman ever married two men in the time of Baha'u'llah. This could merely be a function of Baha'is being subjected to Islamic law, which had a clear prohibition of female polygamy.

### Consent of Both Partners and Parents

Both the man and woman must consent to marriage. Neither can be forced to marry against their wishes. Also, marriage requires the person of all parents of both the bride and the groom. Baha'u'llah says it is to prevent discord or resentment among may arise the couple.

This also does not mean there must be arranged marriages.

He also says there are other purposes.

### Virginity

The husband is allowed to choose a virgin, but it is not a requirement. The implication of this verse is there is no punishment for the woman if she is not a virgin.

### Dowry

A marriage cannot be consummated without the payment of a dowry by the groom to the bride. If the couple lives in the city, the dowry is based on 19 mithqáls (92.34) of gold. If they are in a village, 19 mithqáls of silver. The groom can give up to 95 mithqáls, but is not allowed to exceed it.

#### Gold

<iframe src="https://www.kitco.com/gold-price-today-usa/" width="600" height="400">

</iframe>

#### Silver

<iframe src="https://www.kitco.com/charts/livesilver.html" width="100%" height="400" frameborder="0" allowfullscreen>

</iframe>

There isn't anything specified if one person lives in a city and the other in a village. My initial feeling is it is based on the groom's location or potentially where the married couple intends on living together once married.

Dowry is intended to be a gift which demonstrates the seriousness and sincerity of the man towards the woman. It can also help provide a safety net in case of some unexpected event or hardship for the woman.

### Travel and Abandonment

The following discusses the husband's role and will be framed in that context. However, this should also be able to apply if the spousal roles within the particular marriage are reversed, given the equality of men and women.

The husband is allowed to travel away from home. He must tell his wife how long he will be gone. If he returns and fulfills his promise, he is considered among the righteous.

If he is unable to return at the original specified time and has a genuine reason, he must inform his wife and make every effort to return at the newly specified time. He only has one chance. If he does not inform her of the delay, the wife is free to find another husband 9 months after the original return date. If he does not return by the second time, she is also free to find another husband 9 months after. The wife does not have to find a new husband. Baha'u'llah says God loves those who are patient, but this does not imply the woman would be loved less if she found a new husband.

During the 9 month waiting period, if news reaches her about her husband, she can choose to continue her marriage. She is not required to. God prefers reconciliation, but there should also be no actions which cause enmity.

If the husband passed away or was murdered, confirmed by a news report or 2 just witnesses, anytime during his travel, she also must wait. This could be 9 months, which can give time to grieve. After this, she may find a new husband if she chooses.

If the husband and wife travel together and discord arises between them, the husband must provide the wife with a full year's allowance and return her to where she departed, such as home. The other option is to entrust her to a trustworthy person and whatever is needed to take her to her destination. It would seem the full year's allowance is independent of the requirement to get his wife home. Also, it would also seem there would be room for both to consult on what would be best, such as how much is the allowance.

### Spirit of Joy and Fragrance

Associate with each other in a spirit of joy and fragrance. All that will endure are righteous deeds.

### Oppression and Lewdness

### Do Not Follow a Tyrannical and Wretched One

## Prohibited People

Fathers' Wives

Boys

## Divorce

God prefers unity and concord between a married couple, instead of separation and divorce. Still, divorce is allowed.

No one is allowed to divorce each other three times.

### The Waiting Period

Divorce is allowed if discord or aversion arises, but divorce cannot happen immediately. The couple must wait a year after the intention to divorce is expressed, with the hope the fragrance of love may emanate between them. At the end of the year, if no such fragrance emerged, then divorce is allowed. This also means if the married couple had sex in any form during the year, divorce is not allowed. The husband and wife must be consistent in their intentions.

An allowance will be given to the wife if there is no proven misconduct. The allowance is for the entire year.

If the two divorce, they do have the option to reconcile within one month if neither has married. Baha'u'llah emphasizes mutual love and consent. If the woman has a new husband, a new union is required to restore the relationship. This could mean the original husband would need to go through the original steps to marry, such as having the consent of both sets of parents, the payment of dowry, and a completely new marriage. On the woman's side, it only expresses love and consent, without an explicit requirement to be divorced or unmarried.

### Divorce for Misconduct

If the wife is divorced for proven misconduct, she will not have any allowance during the waiting period.

## Having a Child

As marriage is enjoined upon the believers, and the purpose of marriage is to have a child, having a child is also enjoined upon the believers.

## Children's Education

Fathers are enjoined to education their children. If they fail in this act, the House of Justice must act. This education must include writing and whatever has been prescribed in the Tablet. Educating a child is viewed as educating one of Baha'u'llah's own children. He provides His glory, loving-kindness, and mercy to fathers.

Education must also include learning. Learning could refer to specific subjects, or it could refer to the skills needed to enable a thorough education. Skills could include reading, mathematics, curiosity, critical thinking, problem solving, studying, adaptability, values, and principles.
