---
title: "Fasting"
---

## Who Is Required to Fast?

The age of maturity is the age when a believer is first required to fast, as well as other religious duties. In Questions and Answers, Baha'u'llah defines the age of maturity to be 15 years old for all people. This means anyone under 15 years old should not be expected, required, or forced to fast, even if you are the parent of a child under 15 years old.

Fasting is also not required if any person is ill or if they are in old age. Old age is not defined, but at this time is up to the believer. Any person who is not required to pray may do so if they feel compelled to. A traveler also does not need to fast.

A woman who is menstrating does not have to fast or pray. She is to perform the ablutions and repeat the phrase "Glory be to God, the Lord of Splendor and Beauty" 95 times in a 24-hour period starting at noon. Additionally, if a woman is nurturing a baby, such as in pregnancy or nursing, does not need to fast.

## When?

The month of fasting is the month of 'Ala (Loftiness).

## How?

Refrain from eating and drinking from sunrise to sunset.
