---
title: "Form"
---

And raise up the two houses in the two stations and the places wherein the Throne of your Lord, the Most Merciful, has been established.

## Where?

A House of Justice should be established in every city.

## When?

When the individuals who believe gather in the number of 9 or more.

## Perspective of the Members

The members should regard themselves as entering the presence of God. This means there should be a perspective that within the House of Justice, God is presiding. The Houses of Justice are one of the first official organizations established by God to promote justice and governance. Unlike most religious institutions, it is not designed for worship or other religious acts. Still, this does not mean the members should not act as if their roles are separate from their beliefs, nor separate from the rest of the commands of the Kitab-i-Aqdas.

They will act as the trusted ones and representatives of God for all who dwell on Earth. The functions of a trustee, representative, and other roles will be discussed later, but it should be important to note the trustees and representatives must have the perspective towards all of humankind, not just believers of God and Baha'u'llah. This

They should also consult on the welfare of the servants, those who do believe in God and Baha'u'llah. This welfare, affairs, and consultation would not operate as a clergy, but help ensure the community in each city is taking care of each other according to the guidance given by God.

The members are also commanded to not neglect anything explicitly stated within the Tablet. This demonstrates how important the role of the Houses of Justice serve.

Act in accordance with the ordinances and laws of God, and guard them as you would your eyes, and be not of the losers.
