---
title: "Functions"
---

## Trustees of the Merciful

Use the descendants portion of inheritance to assist orphans, widows, and the general benefit.

For all who dwell on earth

May take from wealthy parents whatever is necessary to educate their children.

From parents who are not wealthy, consultation is required.

Refuge for the poor and needy

## Representatives of God

For all who dwell on earth

## Shephards of the Sheep of God

The sheep of God could only include all believers of Baha'u'llah, but it could also be embracing of all people who believe in God. The members of the House of Justice need to be vigilant against the wolves in garments, suggesting those who may appear as sheep but whose purpose is to harm the believers. These believers are to be protected as if they are the House of Justice member's own children.

## Consult on the Welfare of the Servants

Choose what is best.

## Endowments

Administer endowments dedicated to charitable purposes. These endowments are to be used in elevated places for the Cause. They are to be used for whatever has been commanded by God.

## Enforcement of Laws in the Aqdas

Adultery - 1st offense is 9 mithqáls (38.25g) of gold. 2nd offense is 18 mithqáls (76.5g) of gold. 3rd offense is a humiliating punishment.

Murder

Theft - Banishment, imprisonment. 3rd offense place a mark on the thief's forehead so as to be identified in public as a thief.

Inheritence

Education of children -

Blood Money - 1/3rd of all civil fines from the injury or death of another person. Blood money will be applied to any injuries to the head and body, based upon the severity.
