---
title: "Funding"
---

## From Inheritance

The House of Justice receives the portion from the descendants if the deceased has none. This is 42.8% (1080 of 2520 shares).

The House of Justice receives 33% of the portion from specified heirs from Books 2-6, if the deceased has descendants.

The House of Justice receives 33% of the portion from Books 1-6 if the deceased has nephews and nieces.

The House of Justice receives 100% of the portion from Books 1-6 if the deceased has no nephews and nieces.

The House of Justice receives all 100% of the entire inheritance if the deceased has no inheritors.

This money will be allocated towards:

1.  Orphans
2.  Widows
3.  General benefit

## From Adultery Fines

The House of Justice is to fine both the man and woman 9 mithqáls (38.25g) of gold for the 1st offense and 18 mithqáls (76.5g) of gold for the 2nd offense. The box below shows the current price of gold.

<iframe src="https://www.kitco.com/gold-price-today-usa/" width="600" height="400">

</iframe>

## From Blood Money (Diyah)

One-third of all blood money goes to the House of Justice. Blood money includes any fine or civil judgement against a person for the injury or death of another. The money is to be spent towards justice and the protection of the believers. Note this does not mean the protection of the religion or its institutions, but the protection of the individual believers.

The amount of the fine will be based on the severity of the injury.
