---
title: "Houses in Name of the Lord"
---

The assemblies of creation, or at least anywhere where believers do assemble, are commanded to build houses in the Name of the Lord of all Religions. They are to be build in the best possible manner. This does not mean they need to cost an exorbitant amount of money, nor to be symbols of wealth and success. They are merely to be built in the best way a community is capable of.

There are not supposed to be any pictures or images. This also signifies that in any place where there is worship, even in a congregation, images, pictures, or other likenesses are not to be used. The purpose of the Houses in the Name of the Lord of all Religions is for the remembrance of the Lord, and no other person. This remembrance must be done with spirit and fragrance.

(This may also exclude remembering the Manifestations of God)

## Remembrance with Spirit

Remembrance with Spirit signifies the heart-felt passion which exists when there is sincere belief. There are great examples of this type of worship in various communities, and it involves letting go and being uninhibited. Do not be conscious of the observations of those around you, and just let the Spirit move you and work within you.

## Remembrance with Fragrance

A fragrance is symbolic of that which pleasantly emanates from the source. The fragrance attracts others, like a bee to the sweetest nectar. The remembrance of the Lord in the House should be in a way which is attractive to those who are also seeking to be moved by the Spirit.

There are many things which I have found attractive in congregational worship. Moving music, rhythmic chanting, impassioned praise, and a welcoming community which embraces everyone who comes in as one of their own. There is no judgment, no absolute set way to do things, and no particular script to follow. The remembrance of God is not limited to form or tradition, and when sincerely moved by the Spirit, will always attract the hearts and souls.

## Purpose of the House

The purpose of the House in the Name of the Lord of all Religions is for hearts to be illumined and eyes are comforted. God is the ultimate Lamp, and for a person to witness others who act as though they have the light of God within them is inspiring. It helps to feel that God is active in the hearts of the assembly and in the heart of the community.

When it feels as though God is operating within the assembly, it also moves the heart in a way which gives peace and comfort. It is impossible not to be touched if you are seeking God as your Beloved. The Spirit working through the House and the assembly is a Spirit which can bring hope regardless of the circumstances in life. The Spirit can help inspire pathways for believers to act in the commands of God at home, at work, and within their relationships with family, friends, coworkers, and whomever you may cross paths with.
