---
title: "Inheritance"
---

## Obligations Prior to Inheritance

Inheritance cannot be distributed until certain obligations have been addressed. These obligations include the funeral expenses, debts, and the Right of God payment.

## Inheritance Distribution

Split from the Letter Z (Number 7)

I.  Descendants - Book Ṭ (9) according to number of M, Q, T – ~~540~~  + 540 = 1080 (42.8%)
II. Spouses - Book Ḥ (8) according to number T and F – ~~480~~ - 90 = 390 (15.5%)
III. Fathers - Book Z (7) according to number T and K – ~~420~~ - 90 = 330 (13.1%)
IV. Mothers - Book W (6) according to number R, F, Y, A – ~~360~~ - 90 = 270 (10.7%)
V.  Brothers - Book H (5) according to number Sh – ~~300~~ - 90 = 210 (8.3%)
VI. Sisters - Book D (4) according to number R and M – ~~240~~ - 90 = 150 (6.0%)
VII. Teachers - Book J (3) according to number Q and F – ~~180~~ - 90 = 90 (3.6%)

## How Shares are Calculated

The Books add up to 42. This is the portion each category will receive. For example, the descendants will receive 9 of 42 parts (21.4%). Originally, the part with the according to whichever letters adds up to 2520 shares. 540 of 2520 shares is also 21.4%. If you divide the 2520 shares by the 42 books, each book is worth 60 shares.

Baha'u'llah changed the Babi distribution to double the portion to descendants. This ended up being another 540 shares, with 90 shares being removed from the other 6 categories.

## Inhabited House

If the house is inhabited by descendants, the male descendants inherit the house. If the house is uninhabited, the house could be sold and the proceeds distributed accordingly.

## Specified Garments

Specific garments are to be given to the male descendants. This may not exactly mean common clothing defined by gender roles. Instead, this could mean garments which have a significant meaning or purpose within the family. Ceremonial, spiritual, and culturally significant garments would be included. This also implies these types of garments are not to be sold as part of the estate, and remain a part of the family.

## Heirs Younger Than the Age of Maturity

Their portion is to be managed as a trust by a trustee. The trustee could be a lawyer, institutional investor, a family member, or anyone else specified to act as a trustee. This should be managed as a legal trust. The trustee is not entitled to any of the money within the trust, but is entitled to an agreed upon portion of any profit created from investments. The inheritance will be distributed once the heir reaches the age of maturity.

## Exceptions

If there are no descendants, their portion will go to the House of Justice. (1080 of 2520 shares)

If the deceased has descendants but no other specified heirs, 2/3rds will go to the descendants and 1/3rd will go to the House of Justice. For example, if there is no spouse, 260 of 2520 shares will be added to the descendants for a total of 1340 shares. 130 shares will go to the House of Justice.

If there are no direct heirs from the first 6 categories but there are nephews, nieces, or their children, 2/3rds will go to them and 1/3rd to the House of Justice.

If there are no direct heirs and no nephews, nieces, or their children, the inheritance from the first 6 categories will go to the House of Justice.

## The Spiritual Aspect of Inheritance

Throughout the verses regarding inheritance, Baha'u'llah reminds us that God is bountiful and merciful. No matter the amount of inheritance provided, any person who receives some should be grateful for the bounty provided. There are no exceptions based upon judgments of character or other qualifications to receive. This ensures there is no vying for an increased portion, or any attempts to deny another their portion. This should reduce inter-family conflict over the estates of the deceased.

There is no distribution for random non-profit causes. However, there are possibilities where the House of Justice will receive a portion of the inheritance. With these portions, the House of Justice is to act as trustees for the benefit of orphans, widows, and the general benefit of others. With this in mind, there is an opportunity, such as in the case of a financially successful person to bestow upon certain demographics a substantial bounty. Orphans are pre-maturity people without parents. They generally reach maturity without anything in their name. The inheritance law can change this if the House of Justice acts according to Baha'u'llah's command. Those acting as trustees have an important function in ensuring the loss of a beloved's life is beneficial for the community.
