---
title: "Sovereign Leaders"
---

## Assembly of Kings

The sovereign has come and the kingdom belongs to God. Worship none but God and turn with radiant hearts towards the countenance of your Lord. This is a command that surpasses whatever you possess.

### Wealth

You rejoice in what has been gathered for others, depriving yourselves of the worlds that the Preserved Tablet can reckon. Gathering referring to the practice of accumulating wealth which you will leave once you die. It has occupied you from the ultimate end.

Purify yourself from the stench of the world. The stench is from the decay of morals, materialism, and an attachment to worldly desires.

Hasten towards the Kingdom of your Lord.

### Earthquakes

### Lamentation of Tribes

### Announcement of the Day

### The Most Great Law is Revealed

### Kings are Vassals

Do not let pride prevent you from the Day-Spring of Revelation

Do not let the world veil you from the Creator of the heavens

Rise to serve the Purpose for which you were created by a word from Him.

You are manifestations of power over what has been

You are manifestations of power over what will be.

Leave your houses and turn towards the Kingdom, this will benefit you in both this world and the next.

### Baha'u'llah's Rule

Baha'u'llah desires to rule over hearts, not over your kingdoms. Hearts are the place of Baha'u'llah's vision.

The Kingdom of Names bears witness to this.

### Support Baha'u'llah's Cause

Blessed is the king who arises to support My Cause in My kingdom and detaches himself from all else.

He is one of the people of the Crimson Ark, which God made for the people of Baha. Worthy of being honored, revered, and assisted so that he may conquer cities with the keys of My Name.

He is as the sight of mankind.

He is the most radiant crown upon the brow of creation.

He is the head of generosity for the body of the world.

### Baha'u'llah Endures With Patience

He desires nothing from the assembly of kings, and He endures with patience which has befallen "Us"

### Commands to the Kings

Heal the broken with the hands of justice

Crush the oppressor who is whole with the scourge of the commandments of your Lord.

## Exhortations to Specific Leaders

### To the Emperor of Austria (Franz Joseph I)

He visited Al-Aqsa Mosque but did not enquire about Baha'u'llah, nor sense Him. Baha'u'llah was with the Emperor in all conditions, but the Emporer was clinging to the branch but heedless of the root. Baha'u'llah invited the Emperor to recognize Him instead of clinging to a prior Branch.

### To the King of Berlin (Otto von Bismarck)

Baha'u'llah reminds King Bismarck to remember kings greater than him and their fates. God brought them down from their palaces to their graves.

### To the Kings and Presidents of the Americas

Baha'u'llah instructs them to adorn the temple of dominion with the raiment of justice and piety, and its head with the crown of the remembrance of your Lord.

## Exhortation to Specific Cities and Places

### To the Company of Rome (Italian Rome and Byzantine Rome)

Baha'u'llah hears the sound of the owl among them. Has the intoxication of desire seized you, or are you among the heedless?

### To the Point on the Shore of Two Seas (Istanbul)

The throne of oppression has been established upon you, and the fire of hatred has been ignited within you to such an extent that it has caused lamentation in the Concourse on high and those who circle around the exalted Throne. We see within you the ignorant ruling over the wise, and darkness boasting over the light, while you are in manifest delusion. Your outward adornment has deceived you. By the Lord of creation! It will perish, and the daughters and widows, and the tribes among you, shall weep. Thus does the All-Knowing, the All-Informed give you tidings.

### To the Banks of the Rhine River

We have seen you covered with blood, as the swords of retribution were drawn against you, and again you shall have it.

Franco-Prussian War in early 1870s. Prophecy of new blood.

### The Lamentation of Berlin

We hear the lamentation of Berlin, though she is now in manifest glory.

### To The Land of Ṭā (Tehran)

do not grieve over anything, for God has made you the source of the world's joy. Should He so will, He may bless your throne with one who will rule with justice and gather the scattered sheep of God from the wolves. He shall greet the people of Bahá with joy and gladness. Rejoice in that God has made you the horizon of light (Ta means light or illumination), for in you was born the Dawn of Manifestation, and you were named with this name by which the light of grace shone forth and the heavens and the earth were illumined. Things will be overturned within you, and the masses shall pass judgment upon you. Verily, your Lord is the All-Knowing, the All-Encompassing. Be at peace through the grace of your Lord; indeed, the moments of divine bounty shall not cease from you. Tranquility shall follow the turmoil. Thus has the matter been decreed in a wondrous Book.

### To the Land of Khá (Khurasan)

O Land of Khá! We hear within you the voices of men extolling your Lord, the Self-Sufficient, the Most Exalted. Blessed is the day when the banners of the Names are raised in the Kingdom of Creation in My Most Glorious Name. On that day, the sincere will rejoice in the victory of God, while the disbelievers will lament.

## Exhortation to Believers

No one should object to those who rule over the people. Leave them to what they have and turn towards the hearts.
