---
title: "Leadership Before the House of Justice"
---

## Aghsán (Branches)

The Branches refer to Baha'u'llah's male direct descendants. He had 5 sons who made it to adulthood, and 4 who were surviving by the time the time He ascended to heaven.

If you differ on a matter, refer it to Baha'u'llah's Revelation, for it is sufficient.

### Responsibilities Specified

Manage endowments in the absence of a House of Justice, in accordance to the Tablet of God.

## The Branch to Turn Towards

When the sea of reunion is stilled, and the Book of Origin reaches its end, turn towards Him whom God has willed, the one who branched from this ancient Root.

## People of Baha

Do not speak except by His permission. Only judges according to what God decrees in the Tablet.

If you differ on a matter, refer it to Baha'u'llah's Revelation, which is sufficient.

### Responsibilities Specified

Manage endowments in the absence of a House of Justice, in accordance to the Tablet of God.

The wealthy (along with the House of Justice) should provide what is necessary for those who are incapable of earning a living.
