---
title: "Personal Values"
---

## Fear God

All will perish from a single Word from God.

Do not be of the arrogant

## Love God

## Honor God

## Honor and Love the Manifestation of God

## Sweet Fragrance

## Innate Values

### Piety

Embrace piety.

Adorn your hearts with the garment of piety. Innate to human nature.

### Trustworthiness

Adorn the crown of your heads. Innate to human nature.

He who fulfills his promise is safe from reproach.

### Loyalty

Adorn the crown of your heads. Innate to human nature.

### Truthfulness

Adorn tongues with pure truthfulness. Innate to human nature.

### Courtesy

Adorn bodies with the mantle of courtesy. Innate to human nature.

Freedom removes a person from the realm of courtesy, reducing them to the lowest of the low.

## Be Steadfast

Be manifestations of steadfastness among humanity, so that the doubts of those who have disbelieved in God, when He has appeared with great authority, do not hinder you.

## Fidelity

There is permanence in fidelity, which is faithfulness to obligations, duties, and other observations.

## Be Mindful

Do not despair in calamities, nor rejoice excessively in happiness. Be mindful of and aware of what may come to pass in the end.

## Refinement

Uphold refinement in all manners.

Be an element of refinement among humanity.

This includes eating. Do not immerse hands into dishes and plates without grace. Gold and silver vessels are allowed, but do not allow such adornments replace good manners.

Be adorned with the manners of the people of Paradise.

Eyes will not fall upon what is displeasing to souls.

Includes holding fast to the cord of cleanliness.

Blessed is he who adorns himself with the raiment of manners

## Morals

Blessed is he who adorns himself with the raiment of morals

## Repentant

A person who is afflicted by sin should repent to God. What is defined as sin?

## Dignity

Freedom removes a person from the realm of dignity, reducing them to the lowest of the low.

## Reverence

## Detachment

Abandon what you possess and soar with the wings of detachment above the realm of creation.

Abandon the world, turning your heart towards the Beloved. The vibration of the Word would seize you in such a manner that the greater world would tremble, let alone the lesser world.

## Be Thankful

For God's bounty

For the showers's of His grace that have poured down as a favor from God.

## Righteousness

All that exists will perish and what will endure are righteous deeds.

## Patient

## Wisdom

## Eloquence

## Purity

## Heedful

## Sincerity

## Servitude

Hold firmly to the cord of servitude to the True God.

Through it, your stations will be revealed, your names will be established, and your ranks and remembrances will be elevated in a well-guarded Tablet. Beware that nothing on earth prevents you from attaining this exalted, noble station.

Absolute freedom is found in servitude to God

## Reason

A lack of reason causes people to seek what harms them and abandon what benefits them. They are wanderers.

## Justice

Look with the eye of justice.

## Kindness

## Perceptive

Perceives the fragrance of meanings from the Pen
