---
title: "Prohibitions"
---

## Do Not Rejoice in Your Possessions

In the morning they will belong to another.

There is no permanence in what is possessed.

There is no glory in self-exaltation

Do not collect luxurious ornaments.

Will spend what is possessed to have their names remembered before the Throne.

## Idleness

Do not waste your time in idleness and sloth.

The most despised of men in the sight of God are those who sit idle and seek sustenance.

## Begging

Begging is not permitted, and to him who is asked, it is forbidden to give. It has been enjoined upon everyone to earn a living, and should anyone be incapable, it is for the trustees and the wealthy to provide what is necessary.

## Giving to One Who Begs

## Gambling

Beware lest you use that which will weaken your bodies and harm your minds.

## Opium

Beware lest you use that which will weaken your bodies and harm your minds.

## Forbidden Religious Practices

Do not seclude yourself

Do not seek ascetic hardships

Do not deny yourself what God allows

Do not burden souls with what will make them lethargic and heavy; rather, give them what will lighten them, so they may soar with the wings of the verses to the dawn of clear evidences.

Do not ascend pulpits

## Do Not Follow a Tyrannical and Wretched One

## Do Not Be a Tyrant

## Do Not Be Wicked with Power

## Do Not Destroy What God Has Built

## Do Not Be Wretched

Potential psychological issues associated with tyranny and wretchedness.

## Do Not Be a Wrongdoer

Look with the eye of justice. Beware lest what has been revealed in the former book keep you from this Book, which proclaims the truth: There is no God but Me, the Almighty, the All-Praised.

## Do Not Oppose Baha'u'llah

It is an act of oppression

## Do Not Object to Baha'u'llah

## Do Not Hesitate in Following Baha'u'llah's Command

## Do Not Question What Baha'u'llah Does

This is a word that God has made the adornment and foundation of beliefs, and by it, the deeds of those who act are accepted. Place this word before your eyes, so that the insinuations of those who turn away may not cause you to stumble.

And whoever does not attain this most exalted principle and highest station will be swayed by the winds of doubt and turned by the words of the polytheists. Whoever attains this principle has attained the most great steadfastness.

## Do Not Enter A House Without Permission

Enter not any house in the absence of its owner except with his permission. Adhere to what is proper in all circumstances, and be not among the heedless.

## Do Not Carry Weapons Unless Needed

## Do Not Make Yourselves a Plaything For The Ignorant

## Do Not Be a Deceiver

## Do Not Corrupt the Cause of God

## Do Not Measure the Book by Your Desires

## Do Not Object to the Fragrance of God

## Do Not Withhold Yourselves From the Grace of God

## Do Not Withhold Yourselves From the Bounties of God
