---
title: "Prophecy"
---

## A Clamor In Every Land

## The Throne of Istanbul

It will perish

Daughters and Widows will weep

Tribes among you will weep. Turks, Arabs, Kurds, Greeks, Armenians, Sephardic Jews, Romaniote Jews, Albanians, Circassians, Bosniaks, Levantines. Palestine?

## Blood on the Banks of the Rhine

We have seen you covered with blood, as the swords of retribution were drawn against you, and again you shall have it.

## Lamentation of Berlin

We hear the lamentation of Berlin, though she is now in manifest glory.

## Judgment of Tehran by the Masses

Things will be overturned. The masses will judge you.

Tranquility will follow the turmoil.

## Banners of Names

O Land of Khá! We hear within you the voices of men extolling your Lord, the Self-Sufficient, the Most Exalted. Blessed is the day when the banners of the Names are raised in the Kingdom of Creation in My Most Glorious Name. On that day, the sincere will rejoice in the victory of God, while the disbelievers will lament.

Historical Khorasan included modern day Afghanistan, such as the cities of Harat and Balkh, as well as parts of Turkmenistan, Tajikistan, and Uzbekistan.

Historical religious movements which have been a majority within Khorasan have included Zoroastrianism, Buddhism, and Islam. The area has made a strong contribution to Sufism. Other religions which had a large presence included Manichaeism and Zaydism.
