---
title: "Recitation"
---

The next spiritual practice Baha'u'llah describes in the Kitab-i-Aqdas is recitation. Recitation is a practice which can go hand-in-hand with the obligatory prayers, as a person must be able to recite them to completely fulfill the obligation. Recitation is also a practice which exists outside the obligatory prayers, and is the primary means to make the Word of God known. You can say recitation is a conduit of divine power. If God's Word is reflective of the animating power of God's Breath, recitation is also us animating our souls and the world around us with this animating and creative power of God. Recitation also helps develop emergent virtues derived from the innate virtue loyalty.

## **Who is Required to Recite and When?**

Recitation is a practice, which unlike the obligatory prayers, is not restricted by age or health. All believers are commanded to "recite the verses of God every morning and evening. He who does not recite has not fulfilled the covenant of God and His testament."[^recitation-1] This is a universal obligation without exceptions. Every person, however, may fulfill this obligation according to their own capacities and it will vary in form and effort.

[^recitation-1]: Kitab-i-Aqdas Verse #149

There is no definitive time designated as morning and evening. Simply it could mean the beginning of your day and the end of the day. Traditionally this would mean from dawn or sunrise until noon for the morning, and when light decreases until bedtime for the evening. For people who must work non-traditional schedules, this would be left up to your own circumstances and conscious. For example, if you wake up in the afternoon to work, the afternoon might be your morning and the period after midnight is your evening. What would not change is there are two distinct periods to recite the verses of God, establishing a daily rhythm.

## **What Should Be Recited?**

Baha'u'llah instructs us to recite the verses revealed by God. In Chapter 5, we defined what the Word of God is, which are the verses. Today, this includes everything by Baha'u'llah. He says "Whoever reads a verse from My verses, it is better for him than reading the books of the former and latter generations. This is the declaration of the Merciful, if you are of those who listen. Say: This is true knowledge, if you are of those who recognize."[^recitation-2]

[^recitation-2]: Kitab-i-Aqdas Verse #138

While a person can recite the verses of the Gospel or other former Scriptures from God, we are counseled to use Baha'u'llah's revelation as our primary focus. This does not prohibit reading prior Scriptures, as reading is not exactly recitation. What is excluded from this command? Anything which is not God's words. For example, this book is not from God so you should not use this book for recitation. Any leader after Baha'u'llah who is not a Manifestation of God should not be used for recitation. No scholar deserves to be recited, nor the most beautiful poet. Recitation is reserved for God's Word and God's Word only.

Baha'u'llah's writings include the Kitab-i-Aqdas and many other tablets, letters, and prayers. You can recite in the original Arabic or Persian, but you should do so in a way which you can comprehend. If this means translating to your native language, do so. In today's age, there are many tools capable of translating such as OpenAI's ChatGPT, which was used for the translations used within this book.

## **How Should One Recite?**

Baha'u'llah offers a few guidelines in how a believer should recite the verses of God. The first counsel from Baha'u'llah is not to overburden yourself in reciting the verses of God. Recitation should come with spirit and joy[^recitation-3] and it is welcome for one who is "enraptured by the love of My Name, the Merciful."[^recitation-4] Reciting one verse with spirit and joy is more beneficial for the soul than to recite numerous verses to the point of weariness or listlessness.

[^recitation-3]: Kitab-i-Aqdas Verse #149

[^recitation-4]: Kitab-i-Aqdas Verse #150

I feel this guidance is exceptionally inclusive, as it allows a person to determine what is best for them. Say you struggle with literacy and can only read and understand a few simple words. That's ok! What if you are neurodivergent? Do what you can! Did you just have a long day? God understands. Will I commit a day off to recite for an hour? Yes, if you are able to do so with spirit and joy! Baha'u'llah only wants what is best for you, the individual. God is Most Merciful.

Baha'u'llah also says we should not expect other souls to be overburdened in this spiritual practice. In general, we should not overburden any soul with anything which makes them heavy and lethargic. If a person is reciting with spirit, joy, and love, if they recite in melodious tones, it is one of the most powerful effects known. He says "they perceive from them that which no dominion of the heavens and the earth can equal, and through them they discover the fragrance of My worlds, which today are known only to those endowed with vision from this exalted station. Say, it draws pure hearts to spiritual worlds that cannot be expressed by words nor pointed to by signs. Blessed are those who listen."[^recitation-5]

[^recitation-5]: Kitab-i-Aqdas Verse #116

## Purpose of Recitation

This brings us to the purpose of recitation. Recitation is to be heartfelt. This isn't solely to touch our own heart, but to potentially touch the hearts of a soul which is listless. Heartfelt recitation of God's verses is like a beautiful flower alone in a garden, attracting not only our eyes and noses, but also that of butterflies, bees, and other creatures animated by God's spirit to its fragrance. The verses of God permeate the visible and invisible, inside and outside of us.

This also means recitation can be both a private and public practice. Baha'u'llah describes recitation as one of the practices of the Mashriq'ul-Adhkar. Setting the verses of God to music and singing them would seem to be an important community and cultural practice of believers, according to the style and instrumentation they feel is best. One doesn't have to be a professional singer. Whatever is a most melodious tone for you and heartfelt is what is important. The cool aspect of any spiritual practice is that is is a practice, meant to be practiced. The practice helps develop a skill, such as memorizing, embodying, singing, and feeling the Word of God. No one will ever be perfect but with any practice, time and patience is key.

## Emergent Virtues

With the idea of practice in mind, like prayer, reciting the verses of God helps develop your virtues. For this practice, I want to focus on the innate virtue loyalty. Recitation naturally helps develop loyalty towards God as it expresses a love, honor, and respect that His Word is supreme and able to liberate the souls of yourself and others on its own. Being able to resist the urge to recite other words which are not from God helps express this loyalty. There are also emergent virtues which can be derived from loyalty which are expressed within the Kitab-i-Aqdas. They are fidelity, morality, righteousness, servitude, and steadfastness.

### Fidelity

Fidelity is generally described as the ability to be loyal or faithful to your obligations, duties, and commitments. This is important for all types of relationships, whether they are personal or public such as in business or government. I feel the best way to describe fidelity is through modern sound technology. Fidelity is often the quality used to describe how true to the original sound the reproduced sound is. When we recite in melodious tones, we are being true to the original sound God spoke to us.

Recitation helps express fidelity by honoring the Covenant of God, where a divine trust was placed within our souls. Reciting the verses of God each morning and evening helps renew the vow, reminding the heart the allegiance we have to God, the source of all creation. This practice helps develop fidelity by detaching us from false allegiances, such as to our own ego or even to other worldly sources. These worldly sources could be to religious institutions not grounded by the verses, cultural values, traditions, political ideologies, or even the pleasures of life. Fidelity serves as the compass to keep the soul from drifting aimlessly in the ocean. Imagine what it may have been like for a person to hear the Bab or Baha'u'llah recite the verses of God. This was through just one person. Now imagine if a community of people, say even 10 people reciting the verses of God. This is 10 times the effect, 10 different channels for the Word to pass through and have a positive effect within the world.

### Morality

Morality is a disciplined adherence to standards of right and wrong. Reciting the verses of God helps us understand what these standards are by refining that moral compass. Recitation is a positive action one can take, one which is not grounded in cultural practices of guilt and shame. Guilt is not a virtue. Neither is shame. God's verses transform, not humiliate. They cleanse without accusation.

Imagine the breaths you take when you speak or when you sing. You inhale the life sustaining oxygen from the air, in preparation for your recital. Then you express a verse of God through the exhale. Your voice causes the air to vibrate throughout yourself, even more if you are singing. This vibration is the Word coursing through you. You feel it. You may not automatically embody the morals God desires for us immediately, but with every vibration we are positively effected. The souls of those nearby will also feel these vibrations, these transcendent spiritual truths.

Morality then, does not merely become a matter of law, but a measure of our loyalty to God and to the liberation of our souls. Morality is the true spirit of the law, not the law itself.

### Righteousness

Righteousness is the outward manifestation of our moral clarity. It is an expression of our loyalty to the love and fear of God. Recitation helps shape this virtue by stirring our souls to act in the ways the verses affirm. Righteousness is virtue in action, guided by the full constellation.

As we feel the vibrations of the Word, the soul can feel what is right, what is wrong, what is noble, and what is more base conduct. This isn't merely about legalism, but it is conscientiousness of God's Will as we live the life gifted to us. Righteousness is not what we proclaim publicly, but in how we express our loyalty to God when people are observing and when they are not. Finally, righteousness helps ensure our recitation is sincere, not just a public display or an empty exercise in which we recite solely because we were told to recite. Righteousness ensures we recite because we believe recitation will improve our righteousness.

### Servitude

Servitude is a virtue which can seemingly have negative connotation. In Chapter 5, we discuss freedom and how true freedom comes from believing in and acting on God's Command. Servitude to God is the voluntary offering of the self to the divine Will. It is not an act of forced bondage nor slavery. While prostrating in prayer is the outward symbol of servitude, recitation helps orient our soul to declare "I am Yours." Each verse is a step deeper to loving service, Each verse is a movement towards serving God's cause.

Loyalty expressed through servitude is capable of freeing us from the oppression of others, the tyranny of our own selves, and the illusion of control. Like the flower blooming through heartfelt recitation of God's verses, attracting those who also seek righteousness, fidelity, and morality, we are able to taste the sweet nectar of surrender to the Beloved. It was the Beloved who created the flower for us.

### Steadfastness

Loyalty is constantly being tested in a myriad of ways. Recitation helps fortify the virtue of steadfastness, which is an unwavering persistence in the path of God. True servitude is the world's most difficult path. The examples of the Manifestations of God testify to this. One's body was crucified. Thankfully the soul cannot be crucified. Servitude could seem like suffering to an outsider, but true steadfastness is devotion, grace, strength, and freedom.

Recitation helps develop steadfastness by fortifying the soul through hardship or temptation. When there is a time of crisis, despair, and hope seems lost, the Word can provide us a shield of hope and a sword of light. The Word which has vibrated through us carves these niches of strength within our bones, our muscles, and our hearts. It helps develop our loyalty not just in times of plenty, but in times of tribulation. Even if a tornado were to infiltrate the orchestra, the song would still be played to its completion. The vibrations of the Word of God is like a harp stilling the storm within us. Our steadfastness is the best gift we can offer another, even in reciting the verses when conditions do not seem obviously right to do so.

## A Gentle Reminder

To close this chapter, I want to offer a reminder that these virtues are not absolute. One is not 100% righteous nor 0% righteous, for examples. As we express our loyalty to God, we must do so in ways which does not betray our loyalty to His creation, which can be nurtured through our steadfast servitude. Yes, there are definitely clear commands of what is right and what is wrong. There are also situations where God seems relatively silent for some reason or another. Morality and righteousness must be practiced to increase. They are not automatic for any person, even if your desire is to seem like a saint. In an orchestra, a clarinet can play a melody and then a trumpet. Even though they play the same notes, the sound and its vibrations will be different. When both instruments are played at the same time with the same melody, the sound and its vibrations are amplified and again sounds different.

I offer this prayer Baha'u'llah revealed at the end of the Lawh-i-Ahbab (Tablet to the Friends)

> Glory be to You, my God. You know that I am in prison, calling Your beloved to a share of Your gifts, purely for Your sake. When the idolaters surrounded me from all sides, I remembered You, O Master of names and attributes. I ask You to grant Your servants success in supporting Your cause and elevating Your word, then strengthen them in what manifests the sanctification of Your Essence among Your creatures, and the glorification of Your commands among Your creation. O Lord, enlighten the eyes of their hearts with the light of Your knowledge, and adorn their forms with the embroidery of Your Most Beautiful Names in the realm of creation. Indeed, You are capable of what You will; there is no god but You, the Mighty, the Wise.
