---
title: "Reflection"
---

The next spiritual practice Baha'u'llah describes in the Kitab-i-Aqdas is reflection. Regularly we are commanded to reflect throughout the revelation. I do not mean to be telling puns, but I honestly spent much time reflecting about this chapter and how I want to write it. Reflection as a spiritual practice is not something you commonly hear about, especially in Abrahamic religious circles. I typically viewed reflection as an act of mindful contemplation, perhaps thinking about how Baha'u'llah teaches "O Son of Being! Bring yourself to account each day before you are summoned to account, for death will come suddenly, and you will stand in judgment over your own self."[^reflection-1] Bringing to account had always seemed to be about asking myself if I have done what I was supposed to do, such as obeying Baha'u'llah's laws. What if there is more to this accounting ledger?

[^reflection-1]: The Hidden Words of Arabic #31

As you know by now, we are on Chapter 11 and we haven't even gone over any of the common laws of the Kitab-i-Aqdas. If the Kitab-i-Aqdas is more than a book of laws and is the Choice Sealed Wine, what fragrance might emanate from the commands to reflect which liberates the soul? I realized that maybe I should play with the word reflect. What if reflection is just mindful contemplation but is a soulful exercise, a soul which is designed to be a mirror? The contemplation includes the full temple of the soul, the human body, as well as the soul itself. What does my heart reflect? What does my hand reflect? What do my eyes reflect?

Reflection, if I had to provide a definition, is the process of integrating prayer, recitation, and remembrance into one's soul so as to prepare the soul to honor God. Reflection serves as the bridge towards increased God consciousness within the self. Many religious traditions define this process as the core of their religion. Islam calls it submission to God's will although reflection is missing from the traditional pillars of faith. Reflection is recognizing that our accounting ledger is about how our inner self measures against God's Self. We aren't judging based on the standards of humankind, but we are comparing how we align with God's desire for us. If Muhammad is an example, he regularly retreated to the cave of Hira to reflect, and it was here when he first received revelation. After Jesus was baptized, he spent 40 days in the desert wilderness of Galilee, reflecting and preparing himself for His mission. Moses spent 40 days on Mount Sinai whereupon the law of the Torah eventually emerged. Baha'u'llah, before publicly announcing His mission from God, spent 2 years in Sulaymaniyah as a Naqshbandi Sufi in apart from all He was attached to. Reflection is the way of those best known in faith.

The rest of this chapter will share what Baha'u'llah and the Bab taught about reflection. We will also explore some virtues which emerge from the innate virtue truthfulness through regular reflection.

## Purposes of Reflection

Reflecting is for understanding[^reflection-2] through discovering hidden pearls[^reflection-3] such as pearls of mysteries from the Ocean.[^reflection-4] What are we to understand?

[^reflection-2]: Kitab-i-Aqdas Verse #5

[^reflection-3]: Kitab-i-Aqdas Verse #136

[^reflection-4]: Kitab-i-Aqdas Verse \# 137

### The Choice Sealed Wine

The first thing Baha'u'llah describes for us to understand the hidden pearls of mystery is the Choice Sealed Wine itself, that the Kitab-i-Aqdas is not merely a book of laws. Imagine you are practicing recitation of a verse of the Kitab-i-Aqdas and you take some time to reflect upon the verse. Depending on which spiritual world you are passing through, you might gain an understanding and on a different day, gain another understanding due to passing through a different spiritual world. The hidden pearls are plural, which means there could be countless forms of wisdom to be gained.

### The Bayan

There is a section of the Kitab-i-Aqdas addressed specifically towards the People of Eloquence, also known as the Babi's. He says whoever "reflects on these verses (from the Bayan) and discovers the hidden pearls within them, by God, will find the fragrance of the Merciful emanating from the direction of the prison, and his heart will hasten toward it with longing—nothing will stop him, not the armies of the heavens or the earth."[^reflection-5] Maybe if a person of Baha takes some time to reflect on some verses of the Bayan. The Primal Point says "for nothing has been ordained except for the sake of the Day of the Manifestation of He Whom God shall make manifest, so that if a soul stands before God, there should be no condition within them except refinement—that nothing may be witnessed in them except the love of God."[^reflection-6] The Bayan is a love letter to Baha'u'llah and to reflect the Bayan, is to discover hidden pearls of love for Baha'u'llah.

[^reflection-5]: Kitab-i-Aqdas Verse #136

[^reflection-6]: The Persian Bayan Vahid 8 Gate 6

### The Qiblih

Baha'u'llah says to "reflect regarding the Qiblih[^reflection-7] pearls of mysteries from the ocean." To continue the theme of love and adoration, what would it mean to reflect regarding the Qiblih? Reflection, such as in this case, is not merely to acknowledge a fact, but to feel the nuances from the ocean of meanings. Today, what am I turning towards? Tomorrow, what am I turning away from? Reflection regarding the Qiblih may offer opportunities to identify what we love, and from what we love, what do we turn to more than Baha'u'llah? Do we have multiple points of adoration?

[^reflection-7]: Kitab-i-Aqdas Verse \# 137

### Dawn and Evening on the Mercy and Favors of God

Baha'u'llah tells us to "reflect, during the dawn and evening, on the mercy and favors of God. Give thanks."[^reflection-8] This could be a practice we take during the obligatory prayer. Maybe during the prayer, we take moments to pause and reflect on the portion of the prayer recited. In those moments, we are meditating on a mercy God had bestowed on you. You might not be in prayer, but curled up in bed or your sofa, reflecting on a favor. This is also a practice to help you, even on a burdensome day with some struggle or pain, to identify something good within it. This type of reflection is a difficult practice, but one which may help provide perspective to certain feelings. The heart is a great place for hidden pearls to be unveiled.

[^reflection-8]: Kitab-i-Aqdas Verse #33

### Your Lifecycle

The Kitab-i-Aqdas tells us to "reflect on what you were created from; indeed, all were created from a base fluid."[^reflection-9] Baha'u'llah also says to "reflect on your end, don't be unjust."[^reflection-10] He provides counsel for how we live our lives between our creation and our end. He says "the days of your life pass as the winds blow, and your glory will be rolled up as was the glory of those before you. Reflect, O people, where are your past days, and where are your vanished years? Blessed are the days that were spent in the remembrance of God, and the hours devoted to His praise, the All-Wise.[^reflection-11]

[^reflection-9]: The Suriy-i-Haykal (To the King of Paris)

[^reflection-10]: Kitab-i-Aqdas Verse #148

[^reflection-11]: Kitab-i-Aqdas Verse #40

Reflection here is combined with remembrance. What of God do we remember? How is a name of God manifesting within my life? Is there too much dust on my soul's mirror? Do I praise something more than God? Maybe reflecting on the beginning, knowing all people were created from an egg, a sperm, and the breath of life from God gives us new insights and understandings in how we apply our constellation of virtues. Awareness of the inevitable end may keep a regular perspective for the unique situations we find ourselves in.

### The World and the Conditions of Its People

Reflection is also a bridge between the individual's spiritual life and how we use our life to honor God within the world. Baha'u'llah says to "reflect upon the world and the condition of its people.[^reflection-12] Maybe you are reading a political editorial or having a conversation with a friend regarding a social issue. Emotions are high as there are reasons to feel strongly. What if you reflect during such moments? Your prayers, recitation, and remembrance has prepared you to reflect, in the moment, in how to respond. You may view the world using a map, or view it from an image taken from space. You may notice or feel it's vastness, or its smallness, depending on your reflection. Both can be true. You may feel the joys and pains of people near or far from you. You might feel aspects of oneness and aspects of difference, and see the truths of both aspects. We may observe what we should not do, and the potentials harms which occur when people lack faith, lack love for God, or lack the fear of God.

[^reflection-12]: The Suriy-i-Haykal (To the King of Paris)

Reflection then, is not solely about how our souls reflect God for our own liberation, but reflection is also about the potential liberation of the world and its people. Reflection is what helps make prayer, recitation, and remembrance active within the world. Reflection is the initiator of the Cause of God.

## How Do We Reflect?

> An example is set forth in the supreme word, upon which the entirety of religion is established. Through its utterance, the foundation of all religion is confirmed. In the hour of death, all will speak this word and return to Him. The reflections within mirrors inevitably return to their origin. When the mirrors reflect the image of the sun, they return to it, for their existence began with it. The mirrors’ purpose lies solely in their capacity as mirrors, reflecting the sun from which they originated.[^reflection-13]

[^reflection-13]: The Persian Bayan: Vahid 1 Gate 9

The quote above from the Bab encapsulates perfectly what it means to be a mirror. We are what we reflect, in this life and thereafter. If the purpose of the mirror of the soul is to reflect the light of God, what inhibits the ability to reflect? It could be the orientation of our mirror. Reflection of divine light could be anywhere from 0 to 100%, merely based on the direction our mirror is facing. Another way our ability to reflect is by objects getting between the mirror and the Sun. These objects can be veils, created by ourselves or by others, which are used to keep a person from identifying the light. When a veil exists, what direction will a mirror turn? Other objects can be accumulated dust. This dust can represent a mirror which reflected the light radiantly, but stopped its spiritual practice. Maybe the mirror thought once it attained a spiritual station, that the station was permanent, mistakenly doing what it wanted. Each day which passes allows more dust to settle on the mirror. Eventually, no light reflects as the dust absorbs the light.

How do we reflect to ensure our best reflection, so that our soul may attain the liberation of paradise?

### Detach and Purify

Baha'u'llah says in the Book of Certitude: "the door mentioned in the statement that the servants will not reach the shore of the sea of knowledge except by completely cutting off from everything in the heavens and the earth. Purify yourselves, O people of the earth, so that you may reach the position that God has destined for you, and enter into a pavilion that God has raised in the sky of explanation."

We learned earlier how prayer can help increase the virtue of detachment and how remembrance can help inrease the virtue of purity. These practices help identify what is important for our souls, but we can also learn a lot by what is missing from the obligatory prayers, the verses of God, and the names and attributes of God.

For example, we do not see any description of human race or differences of races. There is not a single writing from the Bab or Baha'u'llah discussing race. Yet, during the European Enlightenment emerging in the 15th century, the idea of race and the subsequent ideologies of race supremacy spread throughout the world as Europe colonized various parts of the globe. By the time Baha'u'llah emerged from the prison of Akka in the late 1870's, nearby Beirut was an intellectual hotspot where race highly influenced the sociopolitical discourse. Beirut was the most common port of entry for pilgrims to Baha'u'llah. It was where his son, Abbas Effendi, sought medical care. Yet, race was notably absent from the Revelation of God through Baha'u'llah. This begs the question: Is race real?

Being able to set aside certain assumptions about what is real or unreal, despite there being common ideas and ideologies current among the people of the age or people of a culture, is vital to true reflection. When Baha'u'llah says certitude can only happen, that we can only attain our highest station by separating ourselves from these assumptions, means we need to be able to detach from these things which act as chains weighing us down. These chains are often described by Baha'u'llah as vain imaginings and idle fancies. A vain imagining is something we create in our own head which is not real and serves no positive purpose in our world of existence. Reflection helps use the spiritual practices God commands to help identify what is real, what is actually true, versus what people may tell is is real and true. This discernment is incredibly important.

Other vain imaginings which people often attach themselves to can include political ideologies or parties, religious identity and labels, conditions of the ego, or even social and economic outcomes. Detach from all save God. To purify in these types of context could include identifying what we love or hate and understanding why. Do we allow our feelings to judge where we shouldn't? Do we blindly follow what is popular or what our families commanded us to follow? Do we get caught up in our own self-doubts and insecurities? These things act to turn our mirrors in directions which reflect corruption, not the radiant light of God. Even if we proclaim "I believe" and still remain attached to things which may not even be real or conducive to the liberation of self, soul, and society, we accumulate a substantial amount of dust on our mirrors.

God is the creator of all, but maybe Satan is merely the corruptor.

### Cleanse the Mirror

So far I had avoided discussing meditation. Meditation is not explicitly commanded by the Bab or Baha'u'llah and it is not a spiritual practice by itself. Yet, meditation can be a tool to help a person reflect. When we have identified what to detach from or purify from, it can be beneficial to take time to be quiet.

> The essence of faith is to speak little and to act abundantly; and if one’s words exceed his deeds, know that his nonexistence is better than his existence, and his demise is better than his survival. The foundation of well-being is silence, consideration of the consequences, and withdrawal from the people.[^reflection-14]

[^reflection-14]: Asl-i-Kullu’l-Khayr (Essence of All Good)

Reflection requires silence, stillness, and a sincere desire to look both inward and while looking outward, deeply. Our spiritual eyes must be piercing. Tools such as meditation or yoga can be useful, as long as the practice themselves are not distracting. Within my own reflection practice, I might curl up on a couch and watch birds eat, sing, and play. Hiking and camping are incredible times to reflect, even if you are with a loved one navigating the depths of your relationship. The most socially isolating time I am able to take is a road day trip, listening to music both vocal and instrumental. I've learned more during these 3 periods of time than I ever have only reading books, in school, or doing the common roles of life. The times of reflection helps consolidate all of these sources of knowledge, feeling, and experience into a form greater than the sum of their parts.

Through this process we can identify a truth about every aspect of our lives, and allow spiritual discernment to increasingly act as our compass. While imperfect, we strive for the process of perfection.

### Reorient

The eventual goal is for the soul to be reoriented, facing away from these attachments, imaginings, and worldly affairs and turned towards God. Baha'u'llah asks us "O Son of the Cloud I call you to eternal life, yet you seek annihilation. Why have you turned away from what I love and turned toward what you desire?"[^reflection-15]

[^reflection-15]: The Hidden Words of Arabic #23

I will close this section with the first paragraphs of Baha'u'llah's Seven Valleys describing the Valley of the Annihilation of Self:

> Upon ascending the lofty stages of bewilderment, the seeker enters the valley of true poverty, the principal annihilation. This stage is marked by the annihilation of the self and the subsistence in God. It is characterized by poverty of the self and richness towards the intended aim. In this state that mentions poverty, it means being poor in terms of what exists in the world of creation, and rich in terms of what exists in the realms of Truth. For when the sincere lover and the concordant beloved reach the meeting of the loved one and the lover, they ignite a fire from the radiance of the loved one’s beauty and the heart’s fire of the lover. This fire burns all the curtains and veils, even burning all that is with them, down to their core and shell, until nothing remains but the beloved. When the ancient qualities manifest themselves, the description of the transient burns completely, as is the case with Moses (Kaleem). In this stage, the one who has reached union is free from all things related to the worldly life. Therefore, if in the company of those who have reached union, one does not find anything limited to the temporal world, whether it be tangible assets or mental thoughts, there is no harm. This is because what is with people is limited to their own limitations, and what is with God is holy beyond that.

## Emergent Virtues From Truthfulness

Reflection helps develop the innate virtue of truthfulness by helping a believer embody what is true and identifying what may be mere illusion. Reflection also helps discern how to act in a given situation which affirms truth and the love of God. Reflection also helps a person go beyond saying "I believe" and being able to help conform their souls to the truth of what belief entails. As God is the source of all truth, a soul seeking God consciousness through reflection can seem to also be a source of truth.

There are other virtues which emerge from truthfulness which reflection helps develop. Here is a quote from the Kitab-i-Badi, where Baha'u'llah is attempting to teach a Babi what the Bab taught in the Bayan, versus what they think was taught in the Bayan.

> Today, knowledge and ignorance, high and low, nearness and distance, truth and falsehood, life and death, maturity and infancy, wisdom and heedlessness, are all distinguished by the confirmation of the manifestation. Whoever believes in Him is of the highest scholars, the noblest people, the most discerning, the most righteous, the most intelligent, the highest, the nearest, the truest, the most precise, and the most understanding. Thus has it been revealed in truth from the realm of supreme might. The Point of the Bayán says in this regard: “Guide, O my God, all who love Me to Your religion. For the matter is from You, and it is the same for all: if the lowest of creation believes in Your proof and signs, they will be the highest; and if the furthest of creation believes, they will be the nearest.” The purpose of these words is that all may know that in God’s sight, the learned ones are those who have come to know Him and have not hesitated in the word “yes.” These are the people of knowledge, the guides of knowledge, the people of infallibility, the source of wisdom, the fountain of eloquence, and the dawn of remembrance. All praiseworthy names return to these souls as long as they remain under the shade of God. Outward knowledge is of no value in this station and never will be.

### Eloquence

The above passage describes eloquence, which Baha'u'llah says the possessors of intelligence must seize.[^reflection-16] Eloquence is the ability to express truth beautifully and clearly. Eloquence is usually associated with speech, but it can also be in the manner we write or how we use our bodies. It is a reflection of the title "Blessed Beauty" where God is the source of all beauty and truth. As we reflect on God's names, the Manifestation of God, and the Truth revealed from them, we may discover the beauty in all aspects of truth. Beauty itself is quite clear and draws people to the truth. Reflection helps not only helps us understand truth for ourselves, but helps us express it in a way which draws the souls waiting to be liberated from that which is not true.

[^reflection-16]: Kitab-i-Aqdas Verse #2

### Heedfulness

In the above quote, heedlessness is in opposition to wisdom. To be heedless, means being unaware or unwilling to fulfill responsibilities, or are unaware of what is around them. It is a foundational reason for apathy, which is inaction of the heart and soul. Reflection helps one become heedful instead of heedless, as we become aware of the reality of the world around us, the nature of souls, the purpose of life, creation, and revelation. We can understand how God's names manifest around us, and maybe exists in ways which aren't obvious. Our awareness of reality increases. Our awareness of our place in the world becomes more clear. This form of truth being revealed through reflection guides our responsibilities to God, to ourselves, and to others near to us and within this world. Reflection encourages us to take heed and act appropriately.

### Perceptive

The above quote describes being attuned to God's sight, came to know God, and never hesitated in action. Perception is required to understand the subtle truths, the truths which are not explicitly defined. These truths could have more than one pathway, and each pathway is like light being refracted through a prism. From one light, we can see red which is truthfully light. We can see green, which is truthfully light. These different colors can bring different lenses and ways to see what is being reflected back to our eyes. Reflection helps us develop the ability not to just see these differences with our physical eyes, but with God's sight which exists within us.

### Wisdom

Reflection helps develop wisdom. Wisdom is not just knowledge of truth, but the just application of knowledge. Reflection helps a person create truth within their entire being. We might read a verse of God and take some time to navigate its application in our lives. There may have been a situation we struggled with and with later reflection, we may have discovered a better way to have navigated the situation or our feelings. Wisdom helps us feel the spirit of religious law and counsel, not just the outward form.

### Reason

> Reason is, in truth, the greatest sign within a human being. Blessed is the soul that attains it. Yet, despite its lofty station and exalted rank, reason is observed to be incapable of comprehending most things. This is because the understanding of reason depends on the testimony of sight. If the eye does not perceive the palm tree, the reason cannot comprehend the realm of fruits, leaves, trees, branches, and boughs within the seed. How, then, can reason understand that there exists something in the world that can burn and reduce all things to ashes, rendering them nonexistent and obliterated? Surely, the hand of God’s power brings that embryo to the realm of perfection. Neither the worlds of God are confined to this world, nor is His power limited by any means.”[^reflection-17]

[^reflection-17]: BH00035 (Unnamed Tablet to Ali Qabl-i-Akbar)

Reason is the alignment of reality and clarity of thought. Sometimes we come across those who seem to value reason or logic as the primary modes of knowing truth, but as Baha'u'llah says, reason alone cannot comprehend most things. Reflection helps develop God's sight within us, so that we can not only know what true, but we can be aligned with it. Reason developed with the other virtues of truthfulness, and in conjunction with the rest of the constellation of virtues, is definitely the greatest sign within us. It can help us distinguish what is a beneficial science, or understand the consequences of actions in both the long-term and short-term. Reflection helps our alignment and adds to our clarity. We can act like a chessmaster, seeing several moves ahead and anticipating potential outcomes.

### Sincerity

> O beloved of My heart! Today the gaze of God is turned with favor upon the righteous deeds of existence, and is drawn to a single word spoken in sincerity. In the sight of God, it is as a recorded book. And a drop of sincere deeds is reckoned as a sea, and this is specific to this Most Great Manifestation—glorified be His majesty and all-encompassing His grace.[^reflection-18]

[^reflection-18]: BH00157 (Unnamed Letter, possibly to a person named Jawad)

Reflection helps solidify potentially the most important virtue animating from truthfulness. Sincerity is the purity of motive in word and action. It helps align the heart and soul so that your actions are truth, without any doubt. Sincerity helps bring peace to whoever you assist, teach, or love as the orientation of your truth is not for personal gain or merely to check a box. You act because you love. You act because you want to share the beauty of truth, you want to share the light and love of God in your words and actions, big and small. Reflection helps understand how we can be better, and how we can ensure truthfulness has the most positive effect.

## In Closing

I hope I did an adequate job writing about reflection. This was a difficult chapter to write, but this is because I personally feel it is an incredibly important practice which is often overlooked. I wanted to approach this with as much truthfulness as I am capable of. Reflection is a bridge towards honoring God, the last spiritual practice this book will cover.

{{< pagebreak >}}
