---
title: "Affectionate Relationships"
---

This chapter is going to look at various kinds of affectionate relationships. Traditionally marriage is the type of relationship most think of when they imagine religion. It is true marriage is the foundation of affectionate relationships, but marriage is not the only kind. Marriage does not magically happen in a vacuum. There are affectionate relationships before marriage, some people choose never to marry, and then there are the situations where these affections end.

Marriage will be the foundation for this chapter. When we understand its purpose, we can consider how affectionate relationships are a deep reflection of our beliefs, regular spiritual practices, our unique constellation of values. They are shaped by our fidelity to the rights of all souls, and the rights and responsibilities we attain after maturity, whether privately or socially.

Much of the marriage law is from the Persian Bayan, with modifications within the Kitab-i-Aqdas. The Bayan is integral to the understanding of Baha'u'llah's marriage law. Symbolically, this is where I would say both Books find union, in the verses regarding the union of two people in wedlock.

## Marriage

Marriage is enjoined upon us.[^relationships-1] Enjoined is also used in the counsel to pray. This means it is part of the divine Doctor's prescription for us to be healthy. The Bab, when he described marriage being enjoined, reinforced the fact it is a firm obligation.[^relationships-2] Baha'u'llah instructed monks to leave their seclusion so they may bear fruits and enter into wedlock.[^relationships-3] To a particular believer, Baha'u'llah said marriage is not permitted to be passed by as it is God's tradition.[^relationships-4]

[^relationships-1]: Kitab-i-Aqdas #63

[^relationships-2]: Persian Bayan Vahid 8, Gate 15

[^relationships-3]: Suriy-i-Haykal

[^relationships-4]: BH10796

### Purpose of Marriage

From the second paragraph of the Marriage Prayer (I am unable to find the first), Baha'u'llah says marriage is a "fortress for well-being and salvation" and "that from you may appear he who will remember Me amongst My servants."[^relationships-5] These are the fruits both the Bab described as "a letter of their own being may remain to proclaim the unity of God."

[^relationships-5]: BH03181

The Bayan had recommended believers to separate if either partner is able to fulfill the obligation of having a baby. In the Suriy-i-Haykal, Baha'u'llah says "But for man, who, on My earth, would remember Me, and how could My attributes and My names be revealed?" Yet, in the Kitab-i-Badi as Baha'u'llah was addressing Azali Bayanis, He rebukes those who say a woman who is barren has no value. Baha'u'llah says those who make such claims have barren hearts, minds, eyes and are deprived of the mercy of God. The implication is every person has a right to create a child, with a responsibility to do so if you are able to. Still, every person maintains their right to love, kindness, and all the other rights if they are unable to create a child. Cruelty is forbidden.

What do you imagine when you hear the phrase a fortress for well-being and salvation? In my imagination, I like to relate the journey of an affectionate relationship and marriage to be similar to the journey of the soul to God the Beloved in Baha'u'llah's "The Seven Valleys" with the valley of unity being where a couple truly feels they are one. This unity helps provide emotional and spiritual stability through such methods as affection, trust, and loyalty. Each spouse is able and willing to shield each other, being each others fortress wall. As each acts in remembrance of each other, they can also reinforce a deeper remembrance of God. This unity helps each spouse develop their individual constellations of virtues, where they help compliment, balance, and merge with their loved one's constellation. These virtues are tested and refined, in good times and in bad. Finally, this fortress for salvation extends to the spouse's fruit, their children and to the community they live in. For the child, it provides stability to nurture their noble birthright. For the community, it serves as a lamp leading by example. In both ways, the married couple ensures God is remembered across generations.

Marriage, in this sense, is the very foundation of the constructive social life. Every mature person has a right to a fortress of well-being and salvation. No person has a responsibility to deny this right under any circumstances.

### Who May Marry and How Many?

Everywhere Baha'u'llah describes marriage, he does define it within the male and female dynamic. BH03181 says "the Lord loves that His handmaidens be joined in marriage to His monotheistic servants." In the Aqdas He says "Beware that you do not exceed two wives. He who is content with one maid will ensure his own tranquility and hers as well." These verses explicitly says marriage is between a man and a woman.

These verses also allow for two wives (bigamy) with a promise of tranquility for a man who prefers monogamy. When looking at the divorce verses, such as in Kitab-i-Aqdas #68, it suggests a woman could also have a second husband. If she takes another husband, a new union is required to restore the first marriage. Baha'u'llah does not specify she must divorce the second husband, although traditionally religious institutions would not allow this.

I will explain within the context of marriage being a form of contract law. The 1st marriage with husband #1 was under Contract #1. They decided to end Contract #1. Therefore, the woman enters into Contract #2 with husband #2. If ex-husband #1 wants to be married again to the woman, they must mutually agree to a new Contract #3. The Kitab-i-Aqdas does not say Contract #2 must end.

Thus, every mature person has the right to marry, and if the law allows, the right to have up to two spouses. Yet this right is tempered by the responsibility to be content with one, for tranquility rests upon the foundation of simplicity and fidelity. The fortress of well-being may stand with two, but its walls are strongest when founded upon unity with one.

### Consent

Marriage requires the consent of both parties.[^relationships-6] Consent can only be obtained by those who have attained maturity. Age 11 marks the earliest age a person can consent to marriage, if they have the means.[^relationships-7] Remember in Chapter 14 the prohibition of pederasty and the right to be free from this practice. No adult has a right to marry a child. One way to interpret the conditions of limitation is that the union of one should be with the union of another who has attained the same level of maturity.

[^relationships-6]: Kitab-i-Aqdas #65

[^relationships-7]: Arabic Bayan, Vahid 8, Gate 15

Consent cannot be obtained through coercion or any type of threat. Consent is formerly recognized for both the man and woman with a phrase signifying their devotion to God.[^relationships-8]

[^relationships-8]: Persian Bayan Vahid 6, Gate 7

> "Indeed, I am for God, the Lord of the heavens and the Lord of the earth, the Lord of all things, the Lord of what is seen and unseen, the Lord of the worlds."

Consent also involves payment of a dowry from the groom to the bride. If the man is living in a city, he must offer between 19 and 95 Bayanic mithqals of gold. For a man living in a village, dowry is the same weight in silver.[^relationships-9] This continues the Bayan's law, which also says the dowry must be in incremental steps of 19, and nothing in between. The groom offers what he is willing or able to pay and the bride chooses to accept. See Appendix 4 regarding the calculation of a Bayanic mithqal.

[^relationships-9]: Kitab-i-Aqdas #65

I feel it should be noted dowry is not a bride price paid to family, nor is symbolic in any way of the bride being property. The dowry is a gift for the bride. It is a symbol of affection towards her while helping provide financial security and stability. Currently, in most countries, women have a lower average income than men, are more likely to be single parents, and face the most risk. I believe those risks are less if the soul's mirror is sincerely facing the Sun of Truth, but things happen, people change, and faith can waiver. While women are equal in the eyes of God, it is also true they often face unequal outcomes. Every believing groom has a responsibility to pay his bride the dowry, and every bride has a right to the dowry.

Baha'u'llah also enjoins consent of both parents of the bride and groom. This helps bring families together. He reminds us of the Qur'an and how that Holy Book relates kindness to parents to belief in the oneness of God.[^relationships-10] He says there are hidden purposes with this command. At best, I believe this serves a purpose of reconciliation for any parent and child who might be estranged, and an opportunity for parents who do not believe in God or Baha'u'llah to learn more about the Cause of God. At worst, two people who love each other may not get married. This can be a profound spiritual test for all involved.

[^relationships-10]: BH02956

In a different tablet, Baha'u'llah discusses how since the Day of Resurrection, families and friendships have struggled when one believes and one does not. Often, the one who believes in Baha'u'llah becomes estranged with the other renouncing them.[^relationships-11] He says as a consequence, relationships are not considered. "Accepting souls are both fathers and sons, for they walk upon one path."

[^relationships-11]: BH00091

In one example, Baha'u'llah nominated himself to be in place of the father of Mirza Asadu'llah Isfani in his marriage with Gawhar in 1882.[^relationships-12] Baha'u'llah could not attend in person, but it does suggest the consent of parents carries a great deal of nuance. Ultimately, the Houses of Justice can appoint individuals to oversee marriages and determine such matters of consent. I think any House of Justice should be careful to focus on love, affection, and unity in such a way discord and resentment is not created.[^relationships-13]

[^relationships-12]: BH00093

[^relationships-13]: Kitab-i-Aqdas #65

### Virginity

Marriage is not dependent on virginity. In a traditional sense, this helps keep marriage as an option for divorcees, widows, and single parents. Outside of the traditional sense, this also helps prevent purity standards from being established. Baha'u'llah in His counsels does regularly refer to chastity.[^relationships-14] There is regular counsel towards women to be chaste when He says "The greatest ornament for the handmaidens hath ever been and still is chastity and virtue. By God! The light of chastity illumineth the horizons of the spiritual worlds and its fragrance reacheth unto the Most Exalted Paradise."[^relationships-15]

[^relationships-14]: BH00726

[^relationships-15]: BH02573

While there is a right to purity and a right to be free from corruption, purity cannot be forced upon anyone. There cannot be any forms of oppression such as virginity inspections imposed upon women. With all of the teachings of Baha'u'llah, especially within the constellation of virtues, premarital sex would be strongly discouraged. This discouragement is based solely on purity, but it is to ensure the bonds of affection are not ruled by lust or other biological impulses of the body. The bonds of affection are to be ruled by spiritual considerations.

If one is solely attached to the concept of virginity, but overlooks other spiritual qualities, a marriage is going to have a difficult time. If a person has premarital sex, but later decides through their spiritual practice to develop chastity, this person can be purified. All of the spiritual virtues have opportunities to shine more brightly and are never completely lost.

To demonstrate this idea, I want to show two examples. In one, Baha'u'llah references Fatimah al-Zahra, the daughter of the Seal of the Prophets Muhammad. She was married to 'Ali ibn Abi Talib and they had at least 4 children. They are known in Shi'a Islam as the Ahl al-Bayt, where the Imams were descended. Baha'u'llah says "O Land of Sad, the Sun of Hijaz asks thee about His family, and the Virgin, the Chosen One, about her sons and daughter."[^relationships-16] How is it a mother is given the title Virgin? This demonstrates virginity is not solely a physical attribute but a spiritual condition for one who acts purely for the sake of God.

[^relationships-16]: BH02352

In the second example, Baha'u'llah is discussing Mirza Yahya, the leader of the Bayani people who did not believe in Baha'u'llah. He says "Every year he would summon a virgin from the outlying regions, ... veiled by the imaginary veils of these idolatrous temples whose reality is evident from their deeds."[^relationships-17] In this example, the coveting of virgins is a form of idolatry which is a veil between you and God.

[^relationships-17]: BH00357

### The Marriage Contract

In the Bayan, once the consent verse is recited by both parties, they affix their seals (signatures) on a document. This is the marriage contract. The Bab requires witnesses representing both spouses, at least ten in total, to attest to dowry, consent, and signing the contract. The purpose of the witnesses is so that both spouses are protected, and neither can deny their marriage nor claim a fake marriage.[^relationships-18] This particularly protects the rights of women from coercion. The Houses of Justice are to ensure marriage is conducted according to the divine law. Each couple can add anything to the contract they feel is important.

[^relationships-18]: BH00035

One addition could be to state if the marriage is monogamous or polygamous. If it is monogamous, there is no possibility of future spouses within that marriage. If it is polygamous, consent would be a vital foundation. Both spouses and the newest spouse would have to each consent to this new union, along with the parents. If any person does not consent, the second marriage cannot be created. It is acceptable if the fortress is open to another, but never in such a way the fortress imprisons one spouse. This ensures each spouse retains the right to be free from coercion, with each bearing responsibility to honor the terms agreed upon.

The marriage contract becomes nullified if dowry is not paid, if one does not return home from travel by an agreed upon time, and if one of the spouses passes away.

### Divorce

This contract can be terminated through divorce. Divorce is an option if any discord or aversion arises between the two, and marriage can continue if there is reconciliation and the fragrance of love emanates between them.[^relationships-19] Divorce requires a one-year waiting period for an opportunity for reconciliation and love to be reestablished. Divorce is only allowed three times, which also means a person is only allowed to be married three times, even if you believe that fourth marriage is guaranteed to never end. During the waiting period, they are still considered legally married and the marriage contract is in effect.

[^relationships-19]: Kitab-i-Aqdas #68

### Discord

Discord in a marriage is any kind of persistent conflict, hostility, aggression, a breach of trust, or even irreconcilable worldviews. If a marriage ever leads to the rights of one or both being violated regularly, it might be good to separate. The responsibility to remain married should never infringe upon the rights to safety, love, kindness, and freedom from oppression. Individual goals which are not mutually beneficial could be a source of argument.

### Aversion

Aversion can be fairly broad in scope. It could be as simple as disliking each other, such as a loss of affection where bonds of intimacy or respect are lost. Aversion could be apathy or other emotional alienation where marriage feels cold or forced. If closeness feels forced or requires a sense of degradation, there is aversion. Aversion could also be from a situation where each others constellation of virtues are no longer aligned, compatible, or changed so significantly, the spiritual bond is severed.

### Adultery

Adultery is a breach of the marriage contract which is enforceable by Houses of Justice. For each man and woman who commits adultery, a fine must be paid of nine Bayanic mithqals of gold.[^relationships-20] For each offense, the fine is doubled from the prior offense. This goes from 9 to 18 to 36 to 72 and so on. Baha'u'llah also specifies a humiliating punishment for a third offense, which would be similar to the punishment for theft, where a mark is placed on the thief's forehead. How the third punishment would take shape is up to the Houses of Justice. The purpose would be to let other people know someone is violating their marriage.

[^relationships-20]: Kitab-i-Aqdas #49

Adultery has also traditionally been treated as including all forms of extra-marital sex, to include people who are not married. One way I have personally considered this is within the scope of the age of maturity. What would happen if two people who are not mature nor independent decide to have consensual sex? It would most likely be financially impossible for both of them to pay 9 Bayanic mithqals of gold. The reason I view adultery as being more about contract law is because of the seriousness when a contract is violated. The Bab and Baha'u'llah repeatedly commanded people to honor their commitments, in both their personal and business lives, reflecting the virtues trustworthiness and fidelity.

## Affectionate Relationships Leading to Marriage

With marriage being a fortress of well-being and salvation, we understand it is a core institution of our social life. Marriage does not happen in a vacuum. It requires the ability to build the bonds of affection and to feel the fragrance of love. Even if these bonds are built, marriage may not be a goal a person has. While there is a traditional ideal, we should be mindful Baha'u'llah says that "God loves unity and concord."[^relationships-21] In seeking an ideal, we shouldn't risk limiting the ways unity and concord can manifest itself in every day life.

[^relationships-21]: Kitab-i-Aqdas #70

### Stage 1 - Friendship

As discussed in Chapter 18, our first foundation is friendliness and fellowship[^relationships-22] even with the followers of other religion.[^relationships-23] We show friendliness through casual interactions, enjoyable shared experiences, and building connections based on mutual interests. Friendliness is characterized by warmth and kindness, not merely politeness. This starts from the moment we greet someone, such as by smiling and showing they are welcome. In our interactions, we engage in light conversation and show genuine interest in their lives, such as who they are, what they do, and what they enjoy. We offer invitations in social activities and accept invitations when possible.

[^relationships-22]: Kitab-i-Aqdas #148

[^relationships-23]: Kitab-i-Aqdas #144

Friendship requires mutual effort. Every person you come across may not be a friend. Baha'u'llah warns us not to associate with the wicked, nor seek companionship with them.[^relationships-24] If someone comes up to you and does not start with a smile and a warm greeting, be cautious. If a stranger is focused on fulfilling their immediate wants, they may not be a friend. Friendship is not a transaction.

[^relationships-24]: Hidden Words of Persian #57

If a relationship only remains a friendship, this friendship is still a vital component in the Cause of God. This is the foundation of all other affectionate relationships

### Stage 2 - Fellowship

Fellowship is a type of relationship which grows from friendship. You take everything you have been doing with your friends and add in some components of commitment, support, sacrifice, and growth. Fellowship adds a strong spiritual component, where you might meet together for spiritual practice, the study of scripture, or acts of service. When there are difficult times, you are there offering encouragement and accountability. You are willing to help, even if it requires a level of self-sacrifice such as sharing time or resources. The conversation can be more challenging, where discussions promote spiritual growth and understanding. This type of challenge can help each other deepen in faith.

There are times where one person desires fellowship, but the other friend or friends may not share this desire. A person should make the effort to achieve fellowship if they desire it, but it should not be done in any oppressive way. If fellowship is not returned, be content to in your friendship.

### Stage 3 - Spiritual Kinship

From fellowship can come a relationship I am calling spiritual kinship. The foundation of this relationship is a shared belief in Baha'u'llah and living in the same Day of God. Distant souls are drawn closer[^relationships-25] by walking one path together, drinking the same nectar, gazing towards the same horizon, and are secluded together in one abode. In spiritual kinship, believers feel as though they are parents, children, and siblings to each other even if this is untrue biologically and legally. This brings a new layer when the Kitab-i-Aqdas says to show love and kindness to your kindred.[^relationships-26]

[^relationships-25]: BH00091

[^relationships-26]: Kitab-i-Aqdas #61

The Hidden Words is, in my opinion, a pillar of spiritual kinship. Throughout the Arabic and Persian versions, Baha'u'llah enjoins us with a declaration "O Son..." where each of us are both a Son of God, a Son of Baha'u'llah in His role as Father, and thus we are siblings of each other. For example, when the Arabic Hidden Word #38 says "grieve not in your distance from us," we can share in our grief as a single family who longs for nearness to God.

### Stage 4 - Courtship

Courtship takes what we have established in friendship, fellowship, and spiritual kinship and adds the fragrance of love. There is a sense of desire and longing to be near all the virtues the other person exemplifies. You love their piety, pure truthfulness, courtesy, loyalty, and trustworthiness, even if the person does not perfectly demonstrate them. You feel safe and secure with them. You can visualize building that fortress together, a fortress which has potential room for descendants. You can see your souls shining within the same mirror, even if they have not yet merged into one.

### Stage 5 - Engagement

If courtship is successful, you are on the path towards marriage. When discussing marriage, Baha'u'llah counsels regarding the matter of marriage by saying "it behooves whosoever desires to enter into any matter to first hold fast to consultation and to act according to what appears therefrom, placing his trust in God, the Protector, the Self-Subsisting."[^relationships-27] This applies to attaining the consent of not only each other, but of the parents (or representatives of the parents). If the consultations are successful, you are engaged. If they are unsuccessful, you are not engaged. Thereupon you can either continue courtship or see if it is best to go back to spiritual kinship, and move on. At no point should this consultation lead to discord or enmity.

[^relationships-27]: BH03310

Once engaged, Baha'u'llah advises delaying the wedding is not recommended.[^relationships-28] He did not define a hard limit though and in the same advice, said the timing of the wedding is entirely up to the couple's discretion. This might be something discussed by the couple and parents in their consultation.

[^relationships-28]: BH01039

### Skipping Stages

Life can be rather complex and messy, and sometimes a person can be ruled by their passions more than their relationship with God. In modern life, it is common to start straight at courtship or a simulated marriage before the foundations of friendship were even established. The more stages which are skipped, the more difficult it is to establish an enduring fortress for salvation and well-being. It is not impossible, but if there is a sense of commitment without fully knowing what is being committed, tranquility may seem elusive.

Spiritual kinship might be the most difficult stage to achieve, especially if the relationship is an interfaith relationship. While Baha'u'llah enjoins friendship and fellowship with those of other religions, it takes a special discernment to identify if you are kin to one of another faith. Can you share in each others spiritual practice? Can you view each other as sharing soul-building experiences even with having different outward labels? Navigating this carefully and intentionally should open the doors of unity without neither having to compromise who they are. God is the Lord of all religions, and is the God to liberate all souls.

## Non-Traditional Relationship Choices

To close this chapter, I want to briefly discuss two concepts which I feel are important for well-functioning communities to understand and accept. The first concept is when a person chooses to remain unmarried, regardless of the relationships they form. They may prefer spiritual kinship or courtship as representing their best way to show love. Celibacy, while not being enjoined upon believers, is a personal option which should be respected.

The second concept is those who express their right to identity in ways which are not easily defined by traditional religious labels and discourse. This can include gender identification, gender-role identification, and preferences in who the feel the fragrance of love for. This is where we should be reminded that God prefers unity and concord, the same God who created all souls noble. Communities need to ensure they are not the cause for discord or enmity, especially for an affectionate relationship to end. On the same token, as expressed in Chapter 16 "The Private Self," we also need to be aware as individuals what is an illusion and what is real. This is a delicate balance individuals and communities must navigate with care and consultation.

I am of the belief the fortress of salvation and well-being should be accessible to all in an inclusive way. All of these affectionate relationships, friendship, fellowship, spiritual kinship, courtship, engagement, and marriage are rights for all mature people, with friendship, fellowship, and spiritual kinship a right of all people from birth. Every person has a responsibility not to deny these rights. God prefers unity and concord.

{{< pagebreak >}}
