---
title: "Unused Teachings"
---

## The Preserved Tablet (Lawh-i-Mahfuz)

## God Loves the Patient

## God Loves Unity and Concord

## God Abhors Separation and Divorce

## By Whom Earthquakes Appeared

## By Whom Tribes Lamented

Except for those who cast aside the world and took what was commanded in the Hidden Tablet.

He who does not recite has not fulfilled the covenant of God and His testament, and whoever turns away from it today is among those who turned away from God in the eternity of eternities.

By Him (Baha'u'llah) the Hour has come

## Seeking Forgiveness

A believer is only allowed to seek forgiveness from God, not from any other person as a religious act. Repentance is only to be sought for by yourself and with God only. Also associated with this act of worship is the prohibition from kissing the hands of another person in an attempt to seek forgiveness.

No person can determine if you are saved, condemned, or any other form of divine judgment. God is Mighty and Forgiving. There are no exclusions based on any act, any perspective, or the like. The Aqdas does say the first command is about believing, which without belief makes you in error no matter what good deed you do. Without belief, you wouldn't even seek forgiveness from God. From who then, would grant you heaven?

## Forbidden Religious Practices

Do not seclude yourself

Do not seek ascetic hardships

Do not deny yourself what God allows

Do not burden souls with what will make them lethargic and heavy; rather, give them what will lighten them, so they may soar with the wings of the verses to the dawn of clear evidences.

Do not ascend pulpits

## Clinging to Another Branch

Baha'u'llah tells the Emperor of Austria he was clinging to the branch, but was heedless of the root. Because of this, he did not recognize Baha'u'llah.

## Prior Revelation from God

Beware that you allow what has been revealed in the former Book from recognizing there is no God but God, the Almighty, the All-Praised.

No one should hold to anything today except that which has appeared in this Revelation. This is the command of God, before and after, and with it He has adorned the scriptures of former generations. This is the mention of God, before and after, with which He has embroidered the fabric of the Book of Existence, if you are of those who perceive. This is the command of God, before and after. Beware lest you be of the abased. Nothing can avail you today, and no one has any refuge but God, the All-Knowing, the All-Wise. Whoever has known Me has known the intended purpose; whoever has turned to Me has turned to the Worshiped One. Thus has it been detailed in the Book, and the matter has been decreed by God, the Lord of the worlds.

Whoever reads a verse from My verses, it is better for him than reading the books of the former and latter generations.

This is the declaration of the Merciful, if you are of those who listen. Say: This is true knowledge, if you are of those who recognize.

Animal Rights

Right to be free from overburdened

A right to hunt with animals. A responsibility not to be excessive.
