---
title: "Verses 1-5"
---

> 1 The first thing that God has prescribed for His servants is the recognition of the dawning place of His Revelation and the source of His command, which is the station of His own Self in the realm of command and creation. Whoever attains this has attained all good, and whoever is deprived of it is indeed among the people of error, even if he performs every good deed. If you attain this exalted station and this supreme horizon, every soul must follow what has been commanded by the Desired One, for both are inseparable, one cannot be accepted without the other. This is what the Source of Inspiration has decreed.
>
> 2 Indeed, those who have been endowed with insight from God see the ordinances of God as the greatest means for the order of the world and the preservation of nations. And those who are heedless of this are like the ignorant masses. We have commanded you to break the boundaries of self and desire, not what has been decreed by the Supreme Pen. It is the spirit of life for those in existence. The seas of wisdom and eloquence have surged forth with the stirring breeze of the All-Merciful. Seize this opportunity, O possessors of intellect. Those who have violated the covenant of God concerning His commands and have turned back on their heels, they are indeed among the people of error in the sight of the Self-Sufficient, the Exalted.
>
> 3 O assembly of the earth, know that My commands are the lamps of My care among My servants and the keys of My mercy for My creation. Thus has the command been revealed from the heaven of the will of your Lord, the Lord of all religions. If anyone were to taste the sweetness of the utterance that has appeared from the mouth of the will of the All-Merciful, he would spend all that he possesses, even if it be the treasures of the entire earth, to uphold one of His commands which have dawned from the horizon of care and grace.
>
> 4 Say, from My laws the fragrance of My garment is diffused, and through them the banners of victory are hoisted on the hills and heights. The tongue of My power has spoken in the dominion of My greatness, addressing My creation: “Carry out My ordinances out of love for My beauty.” Blessed is the lover who has inhaled the fragrance of the Beloved from this word, from which the breezes of bounty have wafted in an indescribable manner. By My life, whoever drinks the nectar of justice from the hands of grace will circle around My commands which have shone forth from the horizon of creativity.
>
> 5 Do not think that We have merely revealed to you the laws; rather, We have unsealed the choice sealed wine with the fingers of might and power. This is attested by what has been sent down by the Pen of Revelation. Reflect, O possessors of understanding.
