---
title: "Warnings to Particular Groups"
---

## Concourse of Ulama (Religious Scholars)

Do not worship the idols of your own desires. Do not view yourself as greater than God. Even Nimrod is in the lowest depths of Hell. Abandon your illusions and turn towards God.

## Assembly of Kings

The sovereign has come and the kingdom belongs to God. Worship none but God and turn with radiant hearts towards the countenance of your Lord. This is a command that surpasses whatever you possess.

### Wealth

You rejoice in what has been gathered for others, depriving yourselves of the worlds that the Preserved Tablet can reckon. Gathering referring to the practice of accumulating wealth which you will leave once you die. It has occupied you from the ultimate end.

Purify yourself from the stench of the world. The stench is from the decay of morals, materialism, and an attachment to worldly desires.

Hasten towards the Kingdom of your Lord.

### Earthquakes

### Lamentation of Tribes

### Announcement of the Day

### The Most Great Law is Revealed

### Kings are Vassals

Do not let pride prevent you from the Day-Spring of Revelation

Do not let the world veil you from the Creator of the heavens

Rise to serve the Purpose for which you were created by a word from Him.

You are manifestations of power over what has been

You are manifestations of power over what will be.

Leave your houses and turn towards the Kingdom, this will benefit you in both this world and the next.

### Baha'u'llah's Rule

Baha'u'llah desires to rule over hearts, not over your kingdoms. Hearts are the place of Baha'u'llah's vision.

The Kingdom of Names bears witness to this.

### Support Baha'u'llah's Cause

Blessed is the king who arises to support My Cause in My kingdom and detaches himself from all else.

He is one of the people of the Crimson Ark, which God made for the people of Baha. Worthy of being honored, revered, and assisted so that he may conquer cities with the keys of My Name.

He is as the sight of mankind.

He is the most radiant crown upon the brow of creation.

He is the head of generosity for the body of the world.
