---
title: "Worship"
---

## Remembrance

Of God

Of Baha'u'llah

Exalt the Lord with joy and gladness

Magnify the Lord with Joy and gladness

Glorify the Lord with Joy and gladness

Rejoice in the joy of the Greatest Name, by which hearts are enraptured and the minds of the near ones are attracted.

Thank Him with joy and spiritual fragrance

Music is a ladder for the ascent of souls to the highest horizon

Whoever is enraptured by the love of My name, the Merciful, shall recite the verses of God in such a manner that the hearts of those who slumber will be moved.

Those who recite the verses of the Most Merciful with the most melodious tones, they perceive from them that which no dominion of the heavens and the earth can equal, and through them they discover the fragrance of My worlds, which today are known only to those endowed with vision from this exalted station. Say, it draws pure hearts to spiritual worlds that cannot be expressed by words nor pointed to by signs. Blessed are those who listen.

Do not conduct remembrance in the streets or marketplaces. Do so in a place designated for remembrance or in your home. This is closer to sincerity and piety.

Recite the verses of God every morning and evening. He who does not recite has not fulfilled the covenant of God and His testament, and whoever turns away from it today is among those who turned away from God in the eternity of eternities. If one should read a single verse with spirit and joy, it is better for him than to recite the holy scriptures of God, the Sovereign, the Self-Subsisting, with listlessness.

Recite the verses of God to the extent that you are not overcome by weariness or sadness.

Do not burden souls with what will make them lethargic and heavy; rather, give them what will lighten them, so they may soar with the wings of the verses to the dawn of clear evidences.

### Beware That Remembrance Becomes a Veil

## Worship in the Houses of the Lord

### Congregational

Congregational worship, also described as the remembrance of the Lord, is encouraged. See the section of the "Houses in the Name of the Lord" regarding their function and purpose.

### Private / Personal

Blessed is the one who turns towards the Mashriqu’l-Adhkár.

Sit in silence, listening to the verses of God.

## Seeking Forgiveness

A believer is only allowed to seek forgiveness from God, not from any other person as a religious act. Repentance is only to be sought for by yourself and with God only. Also associated with this act of worship is the prohibition from kissing the hands of another person in an attempt to seek forgiveness.

No person can determine if you are saved, condemned, or any other form of divine judgment. God is Mighty and Forgiving. There are no exclusions based on any act, any perspective, or the like. The Aqdas does say the first command is about believing, which without belief makes you in error no matter what good deed you do. Without belief, you wouldn't even seek forgiveness from God. From who then, would grant you heaven?

## Reflection

Reflect, during the dawn and evening, on the mercy and favors of God. Give thanks.

reflects on these verses and discovers the hidden pearls within them, by God, will find the fragrance of the Merciful emanating from the direction of the prison, and his heart will hasten toward it with longing—nothing will stop him, not the armies of the heavens or the earth

pearls of mysteries from the ocean

Reflect, O people, on what has been revealed in truth, and ponder it, and do not be of the transgressors.

Reflect on your end, don't be unjust

## Remembering

## Pilgrimage

Men are to perform pilgrimage to the Sacred House. The House is defined as the house where Baha'u'llah lived in Bahji, at Acre. The men are to be able-bodied and have the means to do so. If a man is not able to, it will not be held against him. Women are not required to, but are also allowed to if they so choose.

This difference in ruling is not about gender inequality, or saying women are less able to perform pilgrimage. This is about women having less of an obligation in God's eyes to perform a task. This is about mercy and generosity.

## Engaging in an Occupation

Engaging in an occupation is an act of worship. The purpose is to engage in activities that benefit yourself and others. This requires trusting in God, who is the provider.

Notice the purpose of the occupation is not necessarily to become wealthy, although wealth is one mode to benefit yourself and others. The goal is to find a way to benefit others and trust in God to provide.
